package mnj.ont.model.BOM_automation;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 25 15:07:40 BDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustMnjOntBomRmlineEO_autoImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BomId {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getBomId();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setBomId((Number)value);
            }
        }
        ,
        BomRmlineId {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getBomRmlineId();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setBomRmlineId((Number)value);
            }
        }
        ,
        ItemCategoryId {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getItemCategoryId();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setItemCategoryId((String)value);
            }
        }
        ,
        ItemCode {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getItemCode();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        MeasureUnitId {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getMeasureUnitId();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setMeasureUnitId((String)value);
            }
        }
        ,
        NoOfGarment {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getNoOfGarment();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setNoOfGarment((Number)value);
            }
        }
        ,
        UsageMoUnit {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getUsageMoUnit();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setUsageMoUnit((Number)value);
            }
        }
        ,
        ExtraUsage {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getExtraUsage();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setExtraUsage((Number)value);
            }
        }
        ,
        Rate {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getRate();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setRate((Number)value);
            }
        }
        ,
        ItemRefNo {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getItemRefNo();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setItemRefNo((String)value);
            }
        }
        ,
        ProductionArea {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getProductionArea();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setProductionArea((String)value);
            }
        }
        ,
        RmPlacement {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getRmPlacement();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setRmPlacement((String)value);
            }
        }
        ,
        RmInstruction {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getRmInstruction();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setRmInstruction((String)value);
            }
        }
        ,
        PreCostingLineno {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getPreCostingLineno();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setPreCostingLineno((Number)value);
            }
        }
        ,
        ReleaseDate {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getReleaseDate();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setReleaseDate((Date)value);
            }
        }
        ,
        VersionNumber {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getVersionNumber();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setVersionNumber((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getVersionDate();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        LinkOafId {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getLinkOafId();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setLinkOafId((Number)value);
            }
        }
        ,
        EffectiveStartDate {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getEffectiveStartDate();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setEffectiveStartDate((Date)value);
            }
        }
        ,
        EffectiveEndDate {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getEffectiveEndDate();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setEffectiveEndDate((Date)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        ItemPrefix {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getItemPrefix();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setItemPrefix((String)value);
            }
        }
        ,
        ProcessId {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getProcessId();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setProcessId((Number)value);
            }
        }
        ,
        ProcessDesc {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getProcessDesc();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setProcessDesc((String)value);
            }
        }
        ,
        RmlineType {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getRmlineType();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setRmlineType((String)value);
            }
        }
        ,
        PrintPageSide {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getPrintPageSide();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setPrintPageSide((String)value);
            }
        }
        ,
        LegacyBomid {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getLegacyBomid();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setLegacyBomid((String)value);
            }
        }
        ,
        LegacyBomtrid {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getLegacyBomtrid();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setLegacyBomtrid((String)value);
            }
        }
        ,
        LegacyBomtrCid {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getLegacyBomtrCid();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setLegacyBomtrCid((String)value);
            }
        }
        ,
        ConeDesc {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getConeDesc();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setConeDesc((Number)value);
            }
        }
        ,
        ConeValue {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getConeValue();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setConeValue((Number)value);
            }
        }
        ,
        NoOfCones {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getNoOfCones();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setNoOfCones((Number)value);
            }
        }
        ,
        ThreadUnit {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getThreadUnit();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setThreadUnit((String)value);
            }
        }
        ,
        RequestType {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getRequestType();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setRequestType((String)value);
            }
        }
        ,
        PDesc {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getPDesc();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setPDesc((String)value);
            }
        }
        ,
        PName {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getPName();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setPName((String)value);
            }
        }
        ,
        Position {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getPosition();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setPosition((Number)value);
            }
        }
        ,
        CutP {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getCutP();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setCutP((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute11();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute12();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute13();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute14();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAttribute15();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        VendorId {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getVendorId();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setVendorId((Number)value);
            }
        }
        ,
        BookedQty {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getBookedQty();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setBookedQty((Number)value);
            }
        }
        ,
        Flag {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getFlag();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setFlag((String)value);
            }
        }
        ,
        BookingUom {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getBookingUom();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setBookingUom((String)value);
            }
        }
        ,
        PoQty {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getPoQty();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setPoQty((Number)value);
            }
        }
        ,
        DeliveryDate1 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getDeliveryDate1();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setDeliveryDate1((Date)value);
            }
        }
        ,
        DeliveryDate2 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getDeliveryDate2();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setDeliveryDate2((Date)value);
            }
        }
        ,
        DeliveryDate3 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getDeliveryDate3();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setDeliveryDate3((Date)value);
            }
        }
        ,
        DeliveryDate4 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getDeliveryDate4();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setDeliveryDate4((Date)value);
            }
        }
        ,
        DeliveryDate5 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getDeliveryDate5();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setDeliveryDate5((Date)value);
            }
        }
        ,
        Qty1 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getQty1();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setQty1((Number)value);
            }
        }
        ,
        Qty2 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getQty2();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setQty2((Number)value);
            }
        }
        ,
        Qty3 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getQty3();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setQty3((Number)value);
            }
        }
        ,
        Qty4 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getQty4();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setQty4((Number)value);
            }
        }
        ,
        Qty5 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getQty5();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setQty5((Number)value);
            }
        }
        ,
        UomConvRate {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getUomConvRate();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setUomConvRate((Number)value);
            }
        }
        ,
        OnhandQuantity {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getOnhandQuantity();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setOnhandQuantity((Number)value);
            }
        }
        ,
        AllocateQty {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAllocateQty();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAllocateQty((Number)value);
            }
        }
        ,
        OnhandQty1 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getOnhandQty1();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setOnhandQty1((Number)value);
            }
        }
        ,
        AllocateQty1 {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAllocateQty1();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAllocateQty1((Number)value);
            }
        }
        ,
        AlocateIntrQty {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAlocateIntrQty();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAlocateIntrQty((Number)value);
            }
        }
        ,
        OnhandCgl {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getOnhandCgl();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setOnhandCgl((Number)value);
            }
        }
        ,
        OnhahndGfl {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getOnhahndGfl();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setOnhahndGfl((Number)value);
            }
        }
        ,
        AlocateCgl {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAlocateCgl();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAlocateCgl((Number)value);
            }
        }
        ,
        AlocateGfl {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAlocateGfl();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAlocateGfl((Number)value);
            }
        }
        ,
        AlocateIntrCgl {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAlocateIntrCgl();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAlocateIntrCgl((Number)value);
            }
        }
        ,
        AlocateInterGfl {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAlocateInterGfl();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAlocateInterGfl((Number)value);
            }
        }
        ,
        OrgIdCal {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getOrgIdCal();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setOrgIdCal((Number)value);
            }
        }
        ,
        OrgIdCgl {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getOrgIdCgl();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setOrgIdCgl((Number)value);
            }
        }
        ,
        OrgIdGfl {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getOrgIdGfl();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setOrgIdGfl((Number)value);
            }
        }
        ,
        ApprovalFlag {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getApprovalFlag();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setApprovalFlag((String)value);
            }
        }
        ,
        ExcesBuyReason {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getExcesBuyReason();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setExcesBuyReason((String)value);
            }
        }
        ,
        PricePerUnit {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getPricePerUnit();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setPricePerUnit((Number)value);
            }
        }
        ,
        Total {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getTotal();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setTotal((Number)value);
            }
        }
        ,
        Perntg {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getPerntg();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setPerntg((Number)value);
            }
        }
        ,
        ProjPrQty {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getProjPrQty();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setProjPrQty((Number)value);
            }
        }
        ,
        LineId {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getLineId();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        LeftOverQty {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getLeftOverQty();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setLeftOverQty((Number)value);
            }
        }
        ,
        AdditionalQty {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAdditionalQty();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAdditionalQty((Number)value);
            }
        }
        ,
        ActualPrcnt {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getActualPrcnt();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setActualPrcnt((Number)value);
            }
        }
        ,
        PendingPrcnt {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getPendingPrcnt();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setPendingPrcnt((Number)value);
            }
        }
        ,
        AccumPrcnt {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getAccumPrcnt();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setAccumPrcnt((Number)value);
            }
        }
        ,
        TransferQty {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getTransferQty();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setTransferQty((Number)value);
            }
        }
        ,
        Currency {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getCurrency();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        PurchaseType {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getPurchaseType();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setPurchaseType((String)value);
            }
        }
        ,
        TotalQuantity {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getTotalQuantity();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setTotalQuantity((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(CustMnjOntBomRmlineEO_autoImpl obj) {
                return obj.getRemarks();
            }

            public void put(CustMnjOntBomRmlineEO_autoImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CustMnjOntBomRmlineEO_autoImpl object);

        public abstract void put(CustMnjOntBomRmlineEO_autoImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BOMID = AttributesEnum.BomId.index();
    public static final int BOMRMLINEID = AttributesEnum.BomRmlineId.index();
    public static final int ITEMCATEGORYID = AttributesEnum.ItemCategoryId.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int MEASUREUNITID = AttributesEnum.MeasureUnitId.index();
    public static final int NOOFGARMENT = AttributesEnum.NoOfGarment.index();
    public static final int USAGEMOUNIT = AttributesEnum.UsageMoUnit.index();
    public static final int EXTRAUSAGE = AttributesEnum.ExtraUsage.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int ITEMREFNO = AttributesEnum.ItemRefNo.index();
    public static final int PRODUCTIONAREA = AttributesEnum.ProductionArea.index();
    public static final int RMPLACEMENT = AttributesEnum.RmPlacement.index();
    public static final int RMINSTRUCTION = AttributesEnum.RmInstruction.index();
    public static final int PRECOSTINGLINENO = AttributesEnum.PreCostingLineno.index();
    public static final int RELEASEDATE = AttributesEnum.ReleaseDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int LINKOAFID = AttributesEnum.LinkOafId.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int ITEMPREFIX = AttributesEnum.ItemPrefix.index();
    public static final int PROCESSID = AttributesEnum.ProcessId.index();
    public static final int PROCESSDESC = AttributesEnum.ProcessDesc.index();
    public static final int RMLINETYPE = AttributesEnum.RmlineType.index();
    public static final int PRINTPAGESIDE = AttributesEnum.PrintPageSide.index();
    public static final int LEGACYBOMID = AttributesEnum.LegacyBomid.index();
    public static final int LEGACYBOMTRID = AttributesEnum.LegacyBomtrid.index();
    public static final int LEGACYBOMTRCID = AttributesEnum.LegacyBomtrCid.index();
    public static final int CONEDESC = AttributesEnum.ConeDesc.index();
    public static final int CONEVALUE = AttributesEnum.ConeValue.index();
    public static final int NOOFCONES = AttributesEnum.NoOfCones.index();
    public static final int THREADUNIT = AttributesEnum.ThreadUnit.index();
    public static final int REQUESTTYPE = AttributesEnum.RequestType.index();
    public static final int PDESC = AttributesEnum.PDesc.index();
    public static final int PNAME = AttributesEnum.PName.index();
    public static final int POSITION = AttributesEnum.Position.index();
    public static final int CUTP = AttributesEnum.CutP.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int VENDORID = AttributesEnum.VendorId.index();
    public static final int BOOKEDQTY = AttributesEnum.BookedQty.index();
    public static final int FLAG = AttributesEnum.Flag.index();
    public static final int BOOKINGUOM = AttributesEnum.BookingUom.index();
    public static final int POQTY = AttributesEnum.PoQty.index();
    public static final int DELIVERYDATE1 = AttributesEnum.DeliveryDate1.index();
    public static final int DELIVERYDATE2 = AttributesEnum.DeliveryDate2.index();
    public static final int DELIVERYDATE3 = AttributesEnum.DeliveryDate3.index();
    public static final int DELIVERYDATE4 = AttributesEnum.DeliveryDate4.index();
    public static final int DELIVERYDATE5 = AttributesEnum.DeliveryDate5.index();
    public static final int QTY1 = AttributesEnum.Qty1.index();
    public static final int QTY2 = AttributesEnum.Qty2.index();
    public static final int QTY3 = AttributesEnum.Qty3.index();
    public static final int QTY4 = AttributesEnum.Qty4.index();
    public static final int QTY5 = AttributesEnum.Qty5.index();
    public static final int UOMCONVRATE = AttributesEnum.UomConvRate.index();
    public static final int ONHANDQUANTITY = AttributesEnum.OnhandQuantity.index();
    public static final int ALLOCATEQTY = AttributesEnum.AllocateQty.index();
    public static final int ONHANDQTY1 = AttributesEnum.OnhandQty1.index();
    public static final int ALLOCATEQTY1 = AttributesEnum.AllocateQty1.index();
    public static final int ALOCATEINTRQTY = AttributesEnum.AlocateIntrQty.index();
    public static final int ONHANDCGL = AttributesEnum.OnhandCgl.index();
    public static final int ONHAHNDGFL = AttributesEnum.OnhahndGfl.index();
    public static final int ALOCATECGL = AttributesEnum.AlocateCgl.index();
    public static final int ALOCATEGFL = AttributesEnum.AlocateGfl.index();
    public static final int ALOCATEINTRCGL = AttributesEnum.AlocateIntrCgl.index();
    public static final int ALOCATEINTERGFL = AttributesEnum.AlocateInterGfl.index();
    public static final int ORGIDCAL = AttributesEnum.OrgIdCal.index();
    public static final int ORGIDCGL = AttributesEnum.OrgIdCgl.index();
    public static final int ORGIDGFL = AttributesEnum.OrgIdGfl.index();
    public static final int APPROVALFLAG = AttributesEnum.ApprovalFlag.index();
    public static final int EXCESBUYREASON = AttributesEnum.ExcesBuyReason.index();
    public static final int PRICEPERUNIT = AttributesEnum.PricePerUnit.index();
    public static final int TOTAL = AttributesEnum.Total.index();
    public static final int PERNTG = AttributesEnum.Perntg.index();
    public static final int PROJPRQTY = AttributesEnum.ProjPrQty.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int LEFTOVERQTY = AttributesEnum.LeftOverQty.index();
    public static final int ADDITIONALQTY = AttributesEnum.AdditionalQty.index();
    public static final int ACTUALPRCNT = AttributesEnum.ActualPrcnt.index();
    public static final int PENDINGPRCNT = AttributesEnum.PendingPrcnt.index();
    public static final int ACCUMPRCNT = AttributesEnum.AccumPrcnt.index();
    public static final int TRANSFERQTY = AttributesEnum.TransferQty.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int PURCHASETYPE = AttributesEnum.PurchaseType.index();
    public static final int TOTALQUANTITY = AttributesEnum.TotalQuantity.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustMnjOntBomRmlineEO_autoImpl() {
    }

    /**
     * Gets the attribute value for BomId, using the alias name BomId.
     * @return the BomId
     */
    public Number getBomId() {
        return (Number)getAttributeInternal(BOMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BomId.
     * @param value value to set the BomId
     */
    public void setBomId(Number value) {
        setAttributeInternal(BOMID, value);
    }

    /**
     * Gets the attribute value for BomRmlineId, using the alias name BomRmlineId.
     * @return the BomRmlineId
     */
    public Number getBomRmlineId() {
        return (Number)getAttributeInternal(BOMRMLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BomRmlineId.
     * @param value value to set the BomRmlineId
     */
    public void setBomRmlineId(Number value) {
        setAttributeInternal(BOMRMLINEID, value);
    }

    /**
     * Gets the attribute value for ItemCategoryId, using the alias name ItemCategoryId.
     * @return the ItemCategoryId
     */
    public String getItemCategoryId() {
        return (String)getAttributeInternal(ITEMCATEGORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCategoryId.
     * @param value value to set the ItemCategoryId
     */
    public void setItemCategoryId(String value) {
        setAttributeInternal(ITEMCATEGORYID, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for MeasureUnitId, using the alias name MeasureUnitId.
     * @return the MeasureUnitId
     */
    public String getMeasureUnitId() {
        return (String)getAttributeInternal(MEASUREUNITID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MeasureUnitId.
     * @param value value to set the MeasureUnitId
     */
    public void setMeasureUnitId(String value) {
        setAttributeInternal(MEASUREUNITID, value);
    }

    /**
     * Gets the attribute value for NoOfGarment, using the alias name NoOfGarment.
     * @return the NoOfGarment
     */
    public Number getNoOfGarment() {
        return (Number)getAttributeInternal(NOOFGARMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoOfGarment.
     * @param value value to set the NoOfGarment
     */
    public void setNoOfGarment(Number value) {
        setAttributeInternal(NOOFGARMENT, value);
    }

    /**
     * Gets the attribute value for UsageMoUnit, using the alias name UsageMoUnit.
     * @return the UsageMoUnit
     */
    public Number getUsageMoUnit() {
        return (Number)getAttributeInternal(USAGEMOUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsageMoUnit.
     * @param value value to set the UsageMoUnit
     */
    public void setUsageMoUnit(Number value) {
        setAttributeInternal(USAGEMOUNIT, value);
    }

    /**
     * Gets the attribute value for ExtraUsage, using the alias name ExtraUsage.
     * @return the ExtraUsage
     */
    public Number getExtraUsage() {
        return (Number)getAttributeInternal(EXTRAUSAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraUsage.
     * @param value value to set the ExtraUsage
     */
    public void setExtraUsage(Number value) {
        setAttributeInternal(EXTRAUSAGE, value);
    }

    /**
     * Gets the attribute value for Rate, using the alias name Rate.
     * @return the Rate
     */
    public Number getRate() {
        return (Number)getAttributeInternal(RATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rate.
     * @param value value to set the Rate
     */
    public void setRate(Number value) {
        setAttributeInternal(RATE, value);
    }

    /**
     * Gets the attribute value for ItemRefNo, using the alias name ItemRefNo.
     * @return the ItemRefNo
     */
    public String getItemRefNo() {
        return (String)getAttributeInternal(ITEMREFNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemRefNo.
     * @param value value to set the ItemRefNo
     */
    public void setItemRefNo(String value) {
        setAttributeInternal(ITEMREFNO, value);
    }

    /**
     * Gets the attribute value for ProductionArea, using the alias name ProductionArea.
     * @return the ProductionArea
     */
    public String getProductionArea() {
        return (String)getAttributeInternal(PRODUCTIONAREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductionArea.
     * @param value value to set the ProductionArea
     */
    public void setProductionArea(String value) {
        setAttributeInternal(PRODUCTIONAREA, value);
    }

    /**
     * Gets the attribute value for RmPlacement, using the alias name RmPlacement.
     * @return the RmPlacement
     */
    public String getRmPlacement() {
        return (String)getAttributeInternal(RMPLACEMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for RmPlacement.
     * @param value value to set the RmPlacement
     */
    public void setRmPlacement(String value) {
        setAttributeInternal(RMPLACEMENT, value);
    }

    /**
     * Gets the attribute value for RmInstruction, using the alias name RmInstruction.
     * @return the RmInstruction
     */
    public String getRmInstruction() {
        return (String)getAttributeInternal(RMINSTRUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for RmInstruction.
     * @param value value to set the RmInstruction
     */
    public void setRmInstruction(String value) {
        setAttributeInternal(RMINSTRUCTION, value);
    }

    /**
     * Gets the attribute value for PreCostingLineno, using the alias name PreCostingLineno.
     * @return the PreCostingLineno
     */
    public Number getPreCostingLineno() {
        return (Number)getAttributeInternal(PRECOSTINGLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreCostingLineno.
     * @param value value to set the PreCostingLineno
     */
    public void setPreCostingLineno(Number value) {
        setAttributeInternal(PRECOSTINGLINENO, value);
    }

    /**
     * Gets the attribute value for ReleaseDate, using the alias name ReleaseDate.
     * @return the ReleaseDate
     */
    public Date getReleaseDate() {
        return (Date)getAttributeInternal(RELEASEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReleaseDate.
     * @param value value to set the ReleaseDate
     */
    public void setReleaseDate(Date value) {
        setAttributeInternal(RELEASEDATE, value);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the VersionNumber
     */
    public Number getVersionNumber() {
        return (Number)getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNumber.
     * @param value value to set the VersionNumber
     */
    public void setVersionNumber(Number value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for VersionDate, using the alias name VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date)getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionDate.
     * @param value value to set the VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for LinkOafId, using the alias name LinkOafId.
     * @return the LinkOafId
     */
    public Number getLinkOafId() {
        return (Number)getAttributeInternal(LINKOAFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LinkOafId.
     * @param value value to set the LinkOafId
     */
    public void setLinkOafId(Number value) {
        setAttributeInternal(LINKOAFID, value);
    }

    /**
     * Gets the attribute value for EffectiveStartDate, using the alias name EffectiveStartDate.
     * @return the EffectiveStartDate
     */
    public Date getEffectiveStartDate() {
        return (Date)getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveStartDate.
     * @param value value to set the EffectiveStartDate
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for EffectiveEndDate, using the alias name EffectiveEndDate.
     * @return the EffectiveEndDate
     */
    public Date getEffectiveEndDate() {
        return (Date)getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveEndDate.
     * @param value value to set the EffectiveEndDate
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for InventoryItemId, using the alias name InventoryItemId.
     * @return the InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number)getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InventoryItemId.
     * @param value value to set the InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for ItemPrefix, using the alias name ItemPrefix.
     * @return the ItemPrefix
     */
    public String getItemPrefix() {
        return (String)getAttributeInternal(ITEMPREFIX);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemPrefix.
     * @param value value to set the ItemPrefix
     */
    public void setItemPrefix(String value) {
        setAttributeInternal(ITEMPREFIX, value);
    }

    /**
     * Gets the attribute value for ProcessId, using the alias name ProcessId.
     * @return the ProcessId
     */
    public Number getProcessId() {
        return (Number)getAttributeInternal(PROCESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProcessId.
     * @param value value to set the ProcessId
     */
    public void setProcessId(Number value) {
        setAttributeInternal(PROCESSID, value);
    }

    /**
     * Gets the attribute value for ProcessDesc, using the alias name ProcessDesc.
     * @return the ProcessDesc
     */
    public String getProcessDesc() {
        return (String)getAttributeInternal(PROCESSDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProcessDesc.
     * @param value value to set the ProcessDesc
     */
    public void setProcessDesc(String value) {
        setAttributeInternal(PROCESSDESC, value);
    }

    /**
     * Gets the attribute value for RmlineType, using the alias name RmlineType.
     * @return the RmlineType
     */
    public String getRmlineType() {
        return (String)getAttributeInternal(RMLINETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RmlineType.
     * @param value value to set the RmlineType
     */
    public void setRmlineType(String value) {
        setAttributeInternal(RMLINETYPE, value);
    }

    /**
     * Gets the attribute value for PrintPageSide, using the alias name PrintPageSide.
     * @return the PrintPageSide
     */
    public String getPrintPageSide() {
        return (String)getAttributeInternal(PRINTPAGESIDE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrintPageSide.
     * @param value value to set the PrintPageSide
     */
    public void setPrintPageSide(String value) {
        setAttributeInternal(PRINTPAGESIDE, value);
    }

    /**
     * Gets the attribute value for LegacyBomid, using the alias name LegacyBomid.
     * @return the LegacyBomid
     */
    public String getLegacyBomid() {
        return (String)getAttributeInternal(LEGACYBOMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LegacyBomid.
     * @param value value to set the LegacyBomid
     */
    public void setLegacyBomid(String value) {
        setAttributeInternal(LEGACYBOMID, value);
    }

    /**
     * Gets the attribute value for LegacyBomtrid, using the alias name LegacyBomtrid.
     * @return the LegacyBomtrid
     */
    public String getLegacyBomtrid() {
        return (String)getAttributeInternal(LEGACYBOMTRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LegacyBomtrid.
     * @param value value to set the LegacyBomtrid
     */
    public void setLegacyBomtrid(String value) {
        setAttributeInternal(LEGACYBOMTRID, value);
    }

    /**
     * Gets the attribute value for LegacyBomtrCid, using the alias name LegacyBomtrCid.
     * @return the LegacyBomtrCid
     */
    public String getLegacyBomtrCid() {
        return (String)getAttributeInternal(LEGACYBOMTRCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LegacyBomtrCid.
     * @param value value to set the LegacyBomtrCid
     */
    public void setLegacyBomtrCid(String value) {
        setAttributeInternal(LEGACYBOMTRCID, value);
    }

    /**
     * Gets the attribute value for ConeDesc, using the alias name ConeDesc.
     * @return the ConeDesc
     */
    public Number getConeDesc() {
        return (Number)getAttributeInternal(CONEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConeDesc.
     * @param value value to set the ConeDesc
     */
    public void setConeDesc(Number value) {
        setAttributeInternal(CONEDESC, value);
    }

    /**
     * Gets the attribute value for ConeValue, using the alias name ConeValue.
     * @return the ConeValue
     */
    public Number getConeValue() {
        return (Number)getAttributeInternal(CONEVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConeValue.
     * @param value value to set the ConeValue
     */
    public void setConeValue(Number value) {
        setAttributeInternal(CONEVALUE, value);
    }

    /**
     * Gets the attribute value for NoOfCones, using the alias name NoOfCones.
     * @return the NoOfCones
     */
    public Number getNoOfCones() {
        return (Number)getAttributeInternal(NOOFCONES);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoOfCones.
     * @param value value to set the NoOfCones
     */
    public void setNoOfCones(Number value) {
        setAttributeInternal(NOOFCONES, value);
    }

    /**
     * Gets the attribute value for ThreadUnit, using the alias name ThreadUnit.
     * @return the ThreadUnit
     */
    public String getThreadUnit() {
        return (String)getAttributeInternal(THREADUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ThreadUnit.
     * @param value value to set the ThreadUnit
     */
    public void setThreadUnit(String value) {
        setAttributeInternal(THREADUNIT, value);
    }

    /**
     * Gets the attribute value for RequestType, using the alias name RequestType.
     * @return the RequestType
     */
    public String getRequestType() {
        return (String)getAttributeInternal(REQUESTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestType.
     * @param value value to set the RequestType
     */
    public void setRequestType(String value) {
        setAttributeInternal(REQUESTTYPE, value);
    }

    /**
     * Gets the attribute value for PDesc, using the alias name PDesc.
     * @return the PDesc
     */
    public String getPDesc() {
        return (String)getAttributeInternal(PDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for PDesc.
     * @param value value to set the PDesc
     */
    public void setPDesc(String value) {
        setAttributeInternal(PDESC, value);
    }

    /**
     * Gets the attribute value for PName, using the alias name PName.
     * @return the PName
     */
    public String getPName() {
        return (String)getAttributeInternal(PNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for PName.
     * @param value value to set the PName
     */
    public void setPName(String value) {
        setAttributeInternal(PNAME, value);
    }

    /**
     * Gets the attribute value for Position, using the alias name Position.
     * @return the Position
     */
    public Number getPosition() {
        return (Number)getAttributeInternal(POSITION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Position.
     * @param value value to set the Position
     */
    public void setPosition(Number value) {
        setAttributeInternal(POSITION, value);
    }

    /**
     * Gets the attribute value for CutP, using the alias name CutP.
     * @return the CutP
     */
    public Number getCutP() {
        return (Number)getAttributeInternal(CUTP);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutP.
     * @param value value to set the CutP
     */
    public void setCutP(Number value) {
        setAttributeInternal(CUTP, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for VendorId, using the alias name VendorId.
     * @return the VendorId
     */
    public Number getVendorId() {
        return (Number)getAttributeInternal(VENDORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorId.
     * @param value value to set the VendorId
     */
    public void setVendorId(Number value) {
        setAttributeInternal(VENDORID, value);
    }

    /**
     * Gets the attribute value for BookedQty, using the alias name BookedQty.
     * @return the BookedQty
     */
    public Number getBookedQty() {
        return (Number)getAttributeInternal(BOOKEDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookedQty.
     * @param value value to set the BookedQty
     */
    public void setBookedQty(Number value) {
        setAttributeInternal(BOOKEDQTY, value);
    }

    /**
     * Gets the attribute value for Flag, using the alias name Flag.
     * @return the Flag
     */
    public String getFlag() {
        return (String)getAttributeInternal(FLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for Flag.
     * @param value value to set the Flag
     */
    public void setFlag(String value) {
        setAttributeInternal(FLAG, value);
    }

    /**
     * Gets the attribute value for BookingUom, using the alias name BookingUom.
     * @return the BookingUom
     */
    public String getBookingUom() {
        return (String)getAttributeInternal(BOOKINGUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingUom.
     * @param value value to set the BookingUom
     */
    public void setBookingUom(String value) {
        setAttributeInternal(BOOKINGUOM, value);
    }

    /**
     * Gets the attribute value for PoQty, using the alias name PoQty.
     * @return the PoQty
     */
    public Number getPoQty() {
        return (Number)getAttributeInternal(POQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoQty.
     * @param value value to set the PoQty
     */
    public void setPoQty(Number value) {
        setAttributeInternal(POQTY, value);
    }

    /**
     * Gets the attribute value for DeliveryDate1, using the alias name DeliveryDate1.
     * @return the DeliveryDate1
     */
    public Date getDeliveryDate1() {
        return (Date)getAttributeInternal(DELIVERYDATE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate1.
     * @param value value to set the DeliveryDate1
     */
    public void setDeliveryDate1(Date value) {
        setAttributeInternal(DELIVERYDATE1, value);
    }

    /**
     * Gets the attribute value for DeliveryDate2, using the alias name DeliveryDate2.
     * @return the DeliveryDate2
     */
    public Date getDeliveryDate2() {
        return (Date)getAttributeInternal(DELIVERYDATE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate2.
     * @param value value to set the DeliveryDate2
     */
    public void setDeliveryDate2(Date value) {
        setAttributeInternal(DELIVERYDATE2, value);
    }

    /**
     * Gets the attribute value for DeliveryDate3, using the alias name DeliveryDate3.
     * @return the DeliveryDate3
     */
    public Date getDeliveryDate3() {
        return (Date)getAttributeInternal(DELIVERYDATE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate3.
     * @param value value to set the DeliveryDate3
     */
    public void setDeliveryDate3(Date value) {
        setAttributeInternal(DELIVERYDATE3, value);
    }

    /**
     * Gets the attribute value for DeliveryDate4, using the alias name DeliveryDate4.
     * @return the DeliveryDate4
     */
    public Date getDeliveryDate4() {
        return (Date)getAttributeInternal(DELIVERYDATE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate4.
     * @param value value to set the DeliveryDate4
     */
    public void setDeliveryDate4(Date value) {
        setAttributeInternal(DELIVERYDATE4, value);
    }

    /**
     * Gets the attribute value for DeliveryDate5, using the alias name DeliveryDate5.
     * @return the DeliveryDate5
     */
    public Date getDeliveryDate5() {
        return (Date)getAttributeInternal(DELIVERYDATE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate5.
     * @param value value to set the DeliveryDate5
     */
    public void setDeliveryDate5(Date value) {
        setAttributeInternal(DELIVERYDATE5, value);
    }

    /**
     * Gets the attribute value for Qty1, using the alias name Qty1.
     * @return the Qty1
     */
    public Number getQty1() {
        return (Number)getAttributeInternal(QTY1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty1.
     * @param value value to set the Qty1
     */
    public void setQty1(Number value) {
        setAttributeInternal(QTY1, value);
    }

    /**
     * Gets the attribute value for Qty2, using the alias name Qty2.
     * @return the Qty2
     */
    public Number getQty2() {
        return (Number)getAttributeInternal(QTY2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty2.
     * @param value value to set the Qty2
     */
    public void setQty2(Number value) {
        setAttributeInternal(QTY2, value);
    }

    /**
     * Gets the attribute value for Qty3, using the alias name Qty3.
     * @return the Qty3
     */
    public Number getQty3() {
        return (Number)getAttributeInternal(QTY3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty3.
     * @param value value to set the Qty3
     */
    public void setQty3(Number value) {
        setAttributeInternal(QTY3, value);
    }

    /**
     * Gets the attribute value for Qty4, using the alias name Qty4.
     * @return the Qty4
     */
    public Number getQty4() {
        return (Number)getAttributeInternal(QTY4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty4.
     * @param value value to set the Qty4
     */
    public void setQty4(Number value) {
        setAttributeInternal(QTY4, value);
    }

    /**
     * Gets the attribute value for Qty5, using the alias name Qty5.
     * @return the Qty5
     */
    public Number getQty5() {
        return (Number)getAttributeInternal(QTY5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty5.
     * @param value value to set the Qty5
     */
    public void setQty5(Number value) {
        setAttributeInternal(QTY5, value);
    }

    /**
     * Gets the attribute value for UomConvRate, using the alias name UomConvRate.
     * @return the UomConvRate
     */
    public Number getUomConvRate() {
        return (Number)getAttributeInternal(UOMCONVRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UomConvRate.
     * @param value value to set the UomConvRate
     */
    public void setUomConvRate(Number value) {
        setAttributeInternal(UOMCONVRATE, value);
    }

    /**
     * Gets the attribute value for OnhandQuantity, using the alias name OnhandQuantity.
     * @return the OnhandQuantity
     */
    public Number getOnhandQuantity() {
        return (Number)getAttributeInternal(ONHANDQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OnhandQuantity.
     * @param value value to set the OnhandQuantity
     */
    public void setOnhandQuantity(Number value) {
        setAttributeInternal(ONHANDQUANTITY, value);
    }

    /**
     * Gets the attribute value for AllocateQty, using the alias name AllocateQty.
     * @return the AllocateQty
     */
    public Number getAllocateQty() {
        return (Number)getAttributeInternal(ALLOCATEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllocateQty.
     * @param value value to set the AllocateQty
     */
    public void setAllocateQty(Number value) {
        setAttributeInternal(ALLOCATEQTY, value);
    }

    /**
     * Gets the attribute value for OnhandQty1, using the alias name OnhandQty1.
     * @return the OnhandQty1
     */
    public Number getOnhandQty1() {
        return (Number)getAttributeInternal(ONHANDQTY1);
    }

    /**
     * Sets <code>value</code> as the attribute value for OnhandQty1.
     * @param value value to set the OnhandQty1
     */
    public void setOnhandQty1(Number value) {
        setAttributeInternal(ONHANDQTY1, value);
    }

    /**
     * Gets the attribute value for AllocateQty1, using the alias name AllocateQty1.
     * @return the AllocateQty1
     */
    public Number getAllocateQty1() {
        return (Number)getAttributeInternal(ALLOCATEQTY1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllocateQty1.
     * @param value value to set the AllocateQty1
     */
    public void setAllocateQty1(Number value) {
        setAttributeInternal(ALLOCATEQTY1, value);
    }

    /**
     * Gets the attribute value for AlocateIntrQty, using the alias name AlocateIntrQty.
     * @return the AlocateIntrQty
     */
    public Number getAlocateIntrQty() {
        return (Number)getAttributeInternal(ALOCATEINTRQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlocateIntrQty.
     * @param value value to set the AlocateIntrQty
     */
    public void setAlocateIntrQty(Number value) {
        setAttributeInternal(ALOCATEINTRQTY, value);
    }

    /**
     * Gets the attribute value for OnhandCgl, using the alias name OnhandCgl.
     * @return the OnhandCgl
     */
    public Number getOnhandCgl() {
        return (Number)getAttributeInternal(ONHANDCGL);
    }

    /**
     * Sets <code>value</code> as the attribute value for OnhandCgl.
     * @param value value to set the OnhandCgl
     */
    public void setOnhandCgl(Number value) {
        setAttributeInternal(ONHANDCGL, value);
    }

    /**
     * Gets the attribute value for OnhahndGfl, using the alias name OnhahndGfl.
     * @return the OnhahndGfl
     */
    public Number getOnhahndGfl() {
        return (Number)getAttributeInternal(ONHAHNDGFL);
    }

    /**
     * Sets <code>value</code> as the attribute value for OnhahndGfl.
     * @param value value to set the OnhahndGfl
     */
    public void setOnhahndGfl(Number value) {
        setAttributeInternal(ONHAHNDGFL, value);
    }

    /**
     * Gets the attribute value for AlocateCgl, using the alias name AlocateCgl.
     * @return the AlocateCgl
     */
    public Number getAlocateCgl() {
        return (Number)getAttributeInternal(ALOCATECGL);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlocateCgl.
     * @param value value to set the AlocateCgl
     */
    public void setAlocateCgl(Number value) {
        setAttributeInternal(ALOCATECGL, value);
    }

    /**
     * Gets the attribute value for AlocateGfl, using the alias name AlocateGfl.
     * @return the AlocateGfl
     */
    public Number getAlocateGfl() {
        return (Number)getAttributeInternal(ALOCATEGFL);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlocateGfl.
     * @param value value to set the AlocateGfl
     */
    public void setAlocateGfl(Number value) {
        setAttributeInternal(ALOCATEGFL, value);
    }

    /**
     * Gets the attribute value for AlocateIntrCgl, using the alias name AlocateIntrCgl.
     * @return the AlocateIntrCgl
     */
    public Number getAlocateIntrCgl() {
        return (Number)getAttributeInternal(ALOCATEINTRCGL);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlocateIntrCgl.
     * @param value value to set the AlocateIntrCgl
     */
    public void setAlocateIntrCgl(Number value) {
        setAttributeInternal(ALOCATEINTRCGL, value);
    }

    /**
     * Gets the attribute value for AlocateInterGfl, using the alias name AlocateInterGfl.
     * @return the AlocateInterGfl
     */
    public Number getAlocateInterGfl() {
        return (Number)getAttributeInternal(ALOCATEINTERGFL);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlocateInterGfl.
     * @param value value to set the AlocateInterGfl
     */
    public void setAlocateInterGfl(Number value) {
        setAttributeInternal(ALOCATEINTERGFL, value);
    }

    /**
     * Gets the attribute value for OrgIdCal, using the alias name OrgIdCal.
     * @return the OrgIdCal
     */
    public Number getOrgIdCal() {
        return (Number)getAttributeInternal(ORGIDCAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgIdCal.
     * @param value value to set the OrgIdCal
     */
    public void setOrgIdCal(Number value) {
        setAttributeInternal(ORGIDCAL, value);
    }

    /**
     * Gets the attribute value for OrgIdCgl, using the alias name OrgIdCgl.
     * @return the OrgIdCgl
     */
    public Number getOrgIdCgl() {
        return (Number)getAttributeInternal(ORGIDCGL);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgIdCgl.
     * @param value value to set the OrgIdCgl
     */
    public void setOrgIdCgl(Number value) {
        setAttributeInternal(ORGIDCGL, value);
    }

    /**
     * Gets the attribute value for OrgIdGfl, using the alias name OrgIdGfl.
     * @return the OrgIdGfl
     */
    public Number getOrgIdGfl() {
        return (Number)getAttributeInternal(ORGIDGFL);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgIdGfl.
     * @param value value to set the OrgIdGfl
     */
    public void setOrgIdGfl(Number value) {
        setAttributeInternal(ORGIDGFL, value);
    }

    /**
     * Gets the attribute value for ApprovalFlag, using the alias name ApprovalFlag.
     * @return the ApprovalFlag
     */
    public String getApprovalFlag() {
        return (String)getAttributeInternal(APPROVALFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovalFlag.
     * @param value value to set the ApprovalFlag
     */
    public void setApprovalFlag(String value) {
        setAttributeInternal(APPROVALFLAG, value);
    }

    /**
     * Gets the attribute value for ExcesBuyReason, using the alias name ExcesBuyReason.
     * @return the ExcesBuyReason
     */
    public String getExcesBuyReason() {
        return (String)getAttributeInternal(EXCESBUYREASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExcesBuyReason.
     * @param value value to set the ExcesBuyReason
     */
    public void setExcesBuyReason(String value) {
        setAttributeInternal(EXCESBUYREASON, value);
    }

    /**
     * Gets the attribute value for PricePerUnit, using the alias name PricePerUnit.
     * @return the PricePerUnit
     */
    public Number getPricePerUnit() {
        return (Number)getAttributeInternal(PRICEPERUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PricePerUnit.
     * @param value value to set the PricePerUnit
     */
    public void setPricePerUnit(Number value) {
        setAttributeInternal(PRICEPERUNIT, value);
    }

    /**
     * Gets the attribute value for Total, using the alias name Total.
     * @return the Total
     */
    public Number getTotal() {
        return (Number)getAttributeInternal(TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Total.
     * @param value value to set the Total
     */
    public void setTotal(Number value) {
        setAttributeInternal(TOTAL, value);
    }

    /**
     * Gets the attribute value for Perntg, using the alias name Perntg.
     * @return the Perntg
     */
    public Number getPerntg() {
        return (Number)getAttributeInternal(PERNTG);
    }

    /**
     * Sets <code>value</code> as the attribute value for Perntg.
     * @param value value to set the Perntg
     */
    public void setPerntg(Number value) {
        setAttributeInternal(PERNTG, value);
    }

    /**
     * Gets the attribute value for ProjPrQty, using the alias name ProjPrQty.
     * @return the ProjPrQty
     */
    public Number getProjPrQty() {
        return (Number)getAttributeInternal(PROJPRQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProjPrQty.
     * @param value value to set the ProjPrQty
     */
    public void setProjPrQty(Number value) {
        setAttributeInternal(PROJPRQTY, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for LeftOverQty, using the alias name LeftOverQty.
     * @return the LeftOverQty
     */
    public Number getLeftOverQty() {
        return (Number)getAttributeInternal(LEFTOVERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeftOverQty.
     * @param value value to set the LeftOverQty
     */
    public void setLeftOverQty(Number value) {
        setAttributeInternal(LEFTOVERQTY, value);
    }

    /**
     * Gets the attribute value for AdditionalQty, using the alias name AdditionalQty.
     * @return the AdditionalQty
     */
    public Number getAdditionalQty() {
        return (Number)getAttributeInternal(ADDITIONALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdditionalQty.
     * @param value value to set the AdditionalQty
     */
    public void setAdditionalQty(Number value) {
        setAttributeInternal(ADDITIONALQTY, value);
    }

    /**
     * Gets the attribute value for ActualPrcnt, using the alias name ActualPrcnt.
     * @return the ActualPrcnt
     */
    public Number getActualPrcnt() {
        return (Number)getAttributeInternal(ACTUALPRCNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualPrcnt.
     * @param value value to set the ActualPrcnt
     */
    public void setActualPrcnt(Number value) {
        setAttributeInternal(ACTUALPRCNT, value);
    }

    /**
     * Gets the attribute value for PendingPrcnt, using the alias name PendingPrcnt.
     * @return the PendingPrcnt
     */
    public Number getPendingPrcnt() {
        return (Number)getAttributeInternal(PENDINGPRCNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PendingPrcnt.
     * @param value value to set the PendingPrcnt
     */
    public void setPendingPrcnt(Number value) {
        setAttributeInternal(PENDINGPRCNT, value);
    }

    /**
     * Gets the attribute value for AccumPrcnt, using the alias name AccumPrcnt.
     * @return the AccumPrcnt
     */
    public Number getAccumPrcnt() {
        return (Number)getAttributeInternal(ACCUMPRCNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccumPrcnt.
     * @param value value to set the AccumPrcnt
     */
    public void setAccumPrcnt(Number value) {
        setAttributeInternal(ACCUMPRCNT, value);
    }

    /**
     * Gets the attribute value for TransferQty, using the alias name TransferQty.
     * @return the TransferQty
     */
    public Number getTransferQty() {
        return (Number)getAttributeInternal(TRANSFERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransferQty.
     * @param value value to set the TransferQty
     */
    public void setTransferQty(Number value) {
        setAttributeInternal(TRANSFERQTY, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for PurchaseType, using the alias name PurchaseType.
     * @return the PurchaseType
     */
    public String getPurchaseType() {
        return (String)getAttributeInternal(PURCHASETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PurchaseType.
     * @param value value to set the PurchaseType
     */
    public void setPurchaseType(String value) {
        setAttributeInternal(PURCHASETYPE, value);
    }

    /**
     * Gets the attribute value for TotalQuantity, using the alias name TotalQuantity.
     * @return the TotalQuantity
     */
    public Number getTotalQuantity() {
        return (Number)getAttributeInternal(TOTALQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalQuantity.
     * @param value value to set the TotalQuantity
     */
    public void setTotalQuantity(Number value) {
        setAttributeInternal(TOTALQUANTITY, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param bomRmlineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number bomRmlineId) {
        return new Key(new Object[]{bomRmlineId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.BOM_automation.CustMnjOntBomRmlineEO_auto");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
     protected void create(AttributeList attributeList) {
         super.create(attributeList);
         oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("Cust_Mnj_Ont_Bom_Rmline_S",getDBTransaction());
         oracle.jbo.domain.Number sVal = s.getSequenceNumber();
         setBomRmlineId(sVal);
         setCurrency("USD");
         setPurchaseType("Non-Generic");
     }
    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        ViewObject vo = getDBTransaction().createViewObjectFromQueryStmt("select count(1) from CUST_MNJ_ONT_BOM_OBLINE h where h.BOM_RMLINE_ID ="+getBomRmlineId());
               vo.first();
               int count = 0 ;
               try{
                 count  =  Integer.parseInt(vo.getCurrentRow().getAttribute(0).toString());
               }catch(Exception e){
                   vo.remove();
               }
               if(count == 0 ){
                   super.remove();    
               }else
               {
                String messageText="Child Records exists , can't delete";
                  FacesMessage fm = new FacesMessage(messageText);          
                  fm.setSeverity(FacesMessage.SEVERITY_INFO);
                  FacesContext context = FacesContext.getCurrentInstance();
                  context.addMessage(null, fm);
                   
            }//end of else
            vo.remove();
    }

    /**
     * Add locking logic here.
     */
     public void lock() {
     try {
        super.lock();
     } catch (oracle.jbo.RowInconsistentException e) {
        if (e.getErrorCode().equals("25014")) {
            super.lock();
        } else
            throw e;
     }
     }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
