package mnj.ont.model.lov.vo;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 23 17:14:13 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CurrencyVORowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CurrencyVORowImpl() {
    }
}
