package mnj.ont.model.lov.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 23 17:24:11 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CurrencyVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CurrencyVOImpl() {
    }
}
