package mnj.ont.model.lov.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 15 16:26:31 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class popuplineVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public popuplineVOImpl() {
    }
}
