package mnj.ont.model.lov.vo;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 01 10:26:48 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PurchaseTypeVORowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PurchaseTypeVORowImpl() {
    }
}
