package mnj.ont.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 31 15:24:49 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BomBpoLinesAllVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BomBpoLinesAllVOImpl() {
    }
}
