package mnj.ont.model.views;

import mnj.ont.model.entities.CustMnjOntBomHeaderImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 01 19:23:55 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustMnjOntBomHeaderViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BomId {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBomId();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setBomId((Number)value);
            }
        }
        ,
        BomNumber {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBomNumber();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setBomNumber((Number)value);
            }
        }
        ,
        BpoNo {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBpoNo();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        Orderqty {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getOrderqty();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setOrderqty((Number)value);
            }
        }
        ,
        BomDate {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBomDate();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setBomDate((Date)value);
            }
        }
        ,
        SaleorderId {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getSaleorderId();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setSaleorderId((Number)value);
            }
        }
        ,
        ItemCode {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getItemCode();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        BomStatus {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBomStatus();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setBomStatus((String)value);
            }
        }
        ,
        RevisedRemarks {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getRevisedRemarks();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setRevisedRemarks((String)value);
            }
        }
        ,
        ReleaseDate {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getReleaseDate();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setReleaseDate((Date)value);
            }
        }
        ,
        VersionNumber {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getVersionNumber();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setVersionNumber((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getVersionDate();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        LinkOafId {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getLinkOafId();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setLinkOafId((Number)value);
            }
        }
        ,
        EffectiveStartDate {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getEffectiveStartDate();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setEffectiveStartDate((Date)value);
            }
        }
        ,
        EffectiveEndDate {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getEffectiveEndDate();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setEffectiveEndDate((Date)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getLineId();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        UserItemDescription {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getUserItemDescription();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setUserItemDescription((String)value);
            }
        }
        ,
        LegacyBomid {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getLegacyBomid();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setLegacyBomid((String)value);
            }
        }
        ,
        OrgId {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getOrgId();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        Post {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getPost();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setPost((String)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        SaleOrderNumber {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getSaleOrderNumber();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setSaleOrderNumber((Number)value);
            }
        }
        ,
        Buyer {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBuyer();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setBuyer((String)value);
            }
        }
        ,
        SaleOrderNumber2 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getSaleOrderNumber2();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setSaleOrderNumber2((Number)value);
            }
        }
        ,
        BuyerId {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        BpoNoC {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBpoNoC();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setBpoNoC((String)value);
            }
        }
        ,
        BrandC {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBrandC();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setBrandC((String)value);
            }
        }
        ,
        EndUserDescC {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getEndUserDescC();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setEndUserDescC((String)value);
            }
        }
        ,
        FitC {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getFitC();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setFitC((String)value);
            }
        }
        ,
        ItemDescC {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getItemDescC();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setItemDescC((String)value);
            }
        }
        ,
        OrderQtyC {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getOrderQtyC();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setOrderQtyC((String)value);
            }
        }
        ,
        SeasonC {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getSeasonC();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setSeasonC((String)value);
            }
        }
        ,
        StyleNameC {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getStyleNameC();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setStyleNameC((String)value);
            }
        }
        ,
        StyleNoC {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getStyleNoC();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setStyleNoC((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute16();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute17();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute18();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute19();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute20();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute21 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute21();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute21((String)value);
            }
        }
        ,
        Attribute22 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute22();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute22((String)value);
            }
        }
        ,
        Attribute23 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute23();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute23((String)value);
            }
        }
        ,
        Attribute24 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute24();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute24((String)value);
            }
        }
        ,
        Attribute25 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute25();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute25((String)value);
            }
        }
        ,
        Attribute26 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute26();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute26((String)value);
            }
        }
        ,
        Attribute27 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute27();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute27((String)value);
            }
        }
        ,
        Attribute28 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute28();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute28((String)value);
            }
        }
        ,
        Attribute29 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute29();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute29((String)value);
            }
        }
        ,
        Attribute30 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttribute30();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttribute30((String)value);
            }
        }
        ,
        ErrorMessage {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getErrorMessage();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setErrorMessage((String)value);
            }
        }
        ,
        UnitName {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getUnitName();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setUnitName((String)value);
            }
        }
        ,
        ShipmentUnit {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getShipmentUnit();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setShipmentUnit((String)value);
            }
        }
        ,
        Attachemnt {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getAttachemnt();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttachemnt((Number)value);
            }
        }
        ,
        TotOrdQty {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getTotOrdQty();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setTotOrdQty((Number)value);
            }
        }
        ,
        OrderType {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getOrderType();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setOrderType((String)value);
            }
        }
        ,
        Division {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getDivision();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setDivision((String)value);
            }
        }
        ,
        StyleNameNew {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getStyleNameNew();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setStyleNameNew((String)value);
            }
        }
        ,
        CurrentStyleNo {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getCurrentStyleNo();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setCurrentStyleNo((String)value);
            }
        }
        ,
        CurrentStyleName {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getCurrentStyleName();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setCurrentStyleName((String)value);
            }
        }
        ,
        CustMnjOntBomRmlineLinesView {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getCustMnjOntBomRmlineLinesView();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustMnjOntBomOblineDetailsView {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getCustMnjOntBomOblineDetailsView();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BomBpoLinesAllVO {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBomBpoLinesAllVO();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BomLinesPRHistoryVO {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBomLinesPRHistoryVO();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FabricCustomReportVO {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getFabricCustomReportVO();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MaterialSheetVO {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getMaterialSheetVO();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjBomPoDffVO {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getMnjBomPoDffVO();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustMnjOntBomHeaderView1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getCustMnjOntBomHeaderView1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BuyerCriteria1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBuyerCriteria1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BuyerVO1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBuyerVO1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ZipperColorVO1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getZipperColorVO1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ZipperFinishVO1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getZipperFinishVO1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ZipperUniqueCodeVO1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getZipperUniqueCodeVO1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ZipperTypeVO1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getZipperTypeVO1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ThreadSupplierCode1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getThreadSupplierCode1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StyleNameVO1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getStyleNameVO1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OperatingUnitsVO1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getOperatingUnitsVO1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SeasonLOV1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getSeasonLOV1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StyleNoLOV1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getStyleNoLOV1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OrderTypeVO1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getOrderTypeVO1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BomDivisionVO1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getBomDivisionVO1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ShipmentVO1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getShipmentVO1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ReqUnitName1 {
            public Object get(CustMnjOntBomHeaderViewRowImpl obj) {
                return obj.getReqUnitName1();
            }

            public void put(CustMnjOntBomHeaderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CustMnjOntBomHeaderViewRowImpl object);

        public abstract void put(CustMnjOntBomHeaderViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BOMID = AttributesEnum.BomId.index();
    public static final int BOMNUMBER = AttributesEnum.BomNumber.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int ORDERQTY = AttributesEnum.Orderqty.index();
    public static final int BOMDATE = AttributesEnum.BomDate.index();
    public static final int SALEORDERID = AttributesEnum.SaleorderId.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int BOMSTATUS = AttributesEnum.BomStatus.index();
    public static final int REVISEDREMARKS = AttributesEnum.RevisedRemarks.index();
    public static final int RELEASEDATE = AttributesEnum.ReleaseDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int LINKOAFID = AttributesEnum.LinkOafId.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int USERITEMDESCRIPTION = AttributesEnum.UserItemDescription.index();
    public static final int LEGACYBOMID = AttributesEnum.LegacyBomid.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int POST = AttributesEnum.Post.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int SALEORDERNUMBER = AttributesEnum.SaleOrderNumber.index();
    public static final int BUYER = AttributesEnum.Buyer.index();
    public static final int SALEORDERNUMBER2 = AttributesEnum.SaleOrderNumber2.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int BPONOC = AttributesEnum.BpoNoC.index();
    public static final int BRANDC = AttributesEnum.BrandC.index();
    public static final int ENDUSERDESCC = AttributesEnum.EndUserDescC.index();
    public static final int FITC = AttributesEnum.FitC.index();
    public static final int ITEMDESCC = AttributesEnum.ItemDescC.index();
    public static final int ORDERQTYC = AttributesEnum.OrderQtyC.index();
    public static final int SEASONC = AttributesEnum.SeasonC.index();
    public static final int STYLENAMEC = AttributesEnum.StyleNameC.index();
    public static final int STYLENOC = AttributesEnum.StyleNoC.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE27 = AttributesEnum.Attribute27.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE29 = AttributesEnum.Attribute29.index();
    public static final int ATTRIBUTE30 = AttributesEnum.Attribute30.index();
    public static final int ERRORMESSAGE = AttributesEnum.ErrorMessage.index();
    public static final int UNITNAME = AttributesEnum.UnitName.index();
    public static final int SHIPMENTUNIT = AttributesEnum.ShipmentUnit.index();
    public static final int ATTACHEMNT = AttributesEnum.Attachemnt.index();
    public static final int TOTORDQTY = AttributesEnum.TotOrdQty.index();
    public static final int ORDERTYPE = AttributesEnum.OrderType.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int STYLENAMENEW = AttributesEnum.StyleNameNew.index();
    public static final int CURRENTSTYLENO = AttributesEnum.CurrentStyleNo.index();
    public static final int CURRENTSTYLENAME = AttributesEnum.CurrentStyleName.index();
    public static final int CUSTMNJONTBOMRMLINELINESVIEW = AttributesEnum.CustMnjOntBomRmlineLinesView.index();
    public static final int CUSTMNJONTBOMOBLINEDETAILSVIEW = AttributesEnum.CustMnjOntBomOblineDetailsView.index();
    public static final int BOMBPOLINESALLVO = AttributesEnum.BomBpoLinesAllVO.index();
    public static final int BOMLINESPRHISTORYVO = AttributesEnum.BomLinesPRHistoryVO.index();
    public static final int FABRICCUSTOMREPORTVO = AttributesEnum.FabricCustomReportVO.index();
    public static final int MATERIALSHEETVO = AttributesEnum.MaterialSheetVO.index();
    public static final int MNJBOMPODFFVO = AttributesEnum.MnjBomPoDffVO.index();
    public static final int CUSTMNJONTBOMHEADERVIEW1 = AttributesEnum.CustMnjOntBomHeaderView1.index();
    public static final int BUYERCRITERIA1 = AttributesEnum.BuyerCriteria1.index();
    public static final int BUYERVO1 = AttributesEnum.BuyerVO1.index();
    public static final int ZIPPERCOLORVO1 = AttributesEnum.ZipperColorVO1.index();
    public static final int ZIPPERFINISHVO1 = AttributesEnum.ZipperFinishVO1.index();
    public static final int ZIPPERUNIQUECODEVO1 = AttributesEnum.ZipperUniqueCodeVO1.index();
    public static final int ZIPPERTYPEVO1 = AttributesEnum.ZipperTypeVO1.index();
    public static final int THREADSUPPLIERCODE1 = AttributesEnum.ThreadSupplierCode1.index();
    public static final int STYLENAMEVO1 = AttributesEnum.StyleNameVO1.index();
    public static final int OPERATINGUNITSVO1 = AttributesEnum.OperatingUnitsVO1.index();
    public static final int SEASONLOV1 = AttributesEnum.SeasonLOV1.index();
    public static final int STYLENOLOV1 = AttributesEnum.StyleNoLOV1.index();
    public static final int ORDERTYPEVO1 = AttributesEnum.OrderTypeVO1.index();
    public static final int BOMDIVISIONVO1 = AttributesEnum.BomDivisionVO1.index();
    public static final int SHIPMENTVO1 = AttributesEnum.ShipmentVO1.index();
    public static final int REQUNITNAME1 = AttributesEnum.ReqUnitName1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustMnjOntBomHeaderViewRowImpl() {
    }

    /**
     * Gets CustMnjOntBomHeader entity object.
     * @return the CustMnjOntBomHeader
     */
    public CustMnjOntBomHeaderImpl getCustMnjOntBomHeader() {
        return (CustMnjOntBomHeaderImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for BOM_ID using the alias name BomId.
     * @return the BOM_ID
     */
    public Number getBomId() {
        return (Number) getAttributeInternal(BOMID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOM_ID using the alias name BomId.
     * @param value value to set the BOM_ID
     */
    public void setBomId(Number value) {
        setAttributeInternal(BOMID, value);
    }


    /**
     * Gets the attribute value for BOM_NUMBER using the alias name BomNumber.
     * @return the BOM_NUMBER
     */
    public Number getBomNumber() {
        return (Number) getAttributeInternal(BOMNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for BOM_NUMBER using the alias name BomNumber.
     * @param value value to set the BOM_NUMBER
     */
    public void setBomNumber(Number value) {
        setAttributeInternal(BOMNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BpoNo.
     * @return the BpoNo
     */
    public String getBpoNo() {
        return (String) getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BpoNo.
     * @param value value to set the  BpoNo
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Orderqty.
     * @return the Orderqty
     */
    public Number getOrderqty() {
        return (Number) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Orderqty.
     * @param value value to set the  Orderqty
     */
    public void setOrderqty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for BOM_DATE using the alias name BomDate.
     * @return the BOM_DATE
     */
    public Date getBomDate() {
        return (Date) getAttributeInternal(BOMDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BOM_DATE using the alias name BomDate.
     * @param value value to set the BOM_DATE
     */
    public void setBomDate(Date value) {
        setAttributeInternal(BOMDATE, value);
    }

    /**
     * Gets the attribute value for SALEORDER_ID using the alias name SaleorderId.
     * @return the SALEORDER_ID
     */
    public Number getSaleorderId() {
        return (Number) getAttributeInternal(SALEORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALEORDER_ID using the alias name SaleorderId.
     * @param value value to set the SALEORDER_ID
     */
    public void setSaleorderId(Number value) {
        setAttributeInternal(SALEORDERID, value);
    }

    /**
     * Gets the attribute value for ITEM_CODE using the alias name ItemCode.
     * @return the ITEM_CODE
     */
    public String getItemCode() {
        return (String) getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_CODE using the alias name ItemCode.
     * @param value value to set the ITEM_CODE
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for BOM_STATUS using the alias name BomStatus.
     * @return the BOM_STATUS
     */
    public String getBomStatus() {
        return (String) getAttributeInternal(BOMSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for BOM_STATUS using the alias name BomStatus.
     * @param value value to set the BOM_STATUS
     */
    public void setBomStatus(String value) {
        setAttributeInternal(BOMSTATUS, value);
    }

    /**
     * Gets the attribute value for REVISED_REMARKS using the alias name RevisedRemarks.
     * @return the REVISED_REMARKS
     */
    public String getRevisedRemarks() {
        return (String) getAttributeInternal(REVISEDREMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REVISED_REMARKS using the alias name RevisedRemarks.
     * @param value value to set the REVISED_REMARKS
     */
    public void setRevisedRemarks(String value) {
        setAttributeInternal(REVISEDREMARKS, value);
    }

    /**
     * Gets the attribute value for RELEASE_DATE using the alias name ReleaseDate.
     * @return the RELEASE_DATE
     */
    public Date getReleaseDate() {
        return (Date) getAttributeInternal(RELEASEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RELEASE_DATE using the alias name ReleaseDate.
     * @param value value to set the RELEASE_DATE
     */
    public void setReleaseDate(Date value) {
        setAttributeInternal(RELEASEDATE, value);
    }

    /**
     * Gets the attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @return the VERSION_NUMBER
     */
    public Number getVersionNumber() {
        return (Number) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @param value value to set the VERSION_NUMBER
     */
    public void setVersionNumber(Number value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for VERSION_DATE using the alias name VersionDate.
     * @return the VERSION_DATE
     */
    public Date getVersionDate() {
        return (Date) getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_DATE using the alias name VersionDate.
     * @param value value to set the VERSION_DATE
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for LINK_OAF_ID using the alias name LinkOafId.
     * @return the LINK_OAF_ID
     */
    public Number getLinkOafId() {
        return (Number) getAttributeInternal(LINKOAFID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINK_OAF_ID using the alias name LinkOafId.
     * @param value value to set the LINK_OAF_ID
     */
    public void setLinkOafId(Number value) {
        setAttributeInternal(LINKOAFID, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @return the EFFECTIVE_START_DATE
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @param value value to set the EFFECTIVE_START_DATE
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @return the EFFECTIVE_END_DATE
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @param value value to set the EFFECTIVE_END_DATE
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for USER_ITEM_DESCRIPTION using the alias name UserItemDescription.
     * @return the USER_ITEM_DESCRIPTION
     */
    public String getUserItemDescription() {
        return (String) getAttributeInternal(USERITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ITEM_DESCRIPTION using the alias name UserItemDescription.
     * @param value value to set the USER_ITEM_DESCRIPTION
     */
    public void setUserItemDescription(String value) {
        setAttributeInternal(USERITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for LEGACY_BOMID using the alias name LegacyBomid.
     * @return the LEGACY_BOMID
     */
    public String getLegacyBomid() {
        return (String) getAttributeInternal(LEGACYBOMID);
    }

    /**
     * Sets <code>value</code> as attribute value for LEGACY_BOMID using the alias name LegacyBomid.
     * @param value value to set the LEGACY_BOMID
     */
    public void setLegacyBomid(String value) {
        setAttributeInternal(LEGACYBOMID, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for POST using the alias name Post.
     * @return the POST
     */
    public String getPost() {
        return (String) getAttributeInternal(POST);
    }

    /**
     * Sets <code>value</code> as attribute value for POST using the alias name Post.
     * @param value value to set the POST
     */
    public void setPost(String value) {
        setAttributeInternal(POST, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }


    /**
     * Gets the attribute value for the calculated attribute SaleOrderNumber.
     * @return the SaleOrderNumber
     */
    public Number getSaleOrderNumber() {
        return (Number) getAttributeInternal(SALEORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SaleOrderNumber.
     * @param value value to set the  SaleOrderNumber
     */
    public void setSaleOrderNumber(Number value) {
        setAttributeInternal(SALEORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Buyer.
     * @return the Buyer
     */
    public String getBuyer() {
        return (String) getAttributeInternal(BUYER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Buyer.
     * @param value value to set the  Buyer
     */
    public void setBuyer(String value) {
        setAttributeInternal(BUYER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SaleOrderNumber2.
     * @return the SaleOrderNumber2
     */
    public Number getSaleOrderNumber2() {
        return (Number) getAttributeInternal(SALEORDERNUMBER2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SaleOrderNumber2.
     * @param value value to set the  SaleOrderNumber2
     */
    public void setSaleOrderNumber2(Number value) {
        setAttributeInternal(SALEORDERNUMBER2, value);
    }


    /**
     * Gets the attribute value for BUYER_ID using the alias name BuyerId.
     * @return the BUYER_ID
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUYER_ID using the alias name BuyerId.
     * @param value value to set the BUYER_ID
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for BPO_NO_C using the alias name BpoNoC.
     * @return the BPO_NO_C
     */
    public String getBpoNoC() {
        return (String) getAttributeInternal(BPONOC);
    }

    /**
     * Sets <code>value</code> as attribute value for BPO_NO_C using the alias name BpoNoC.
     * @param value value to set the BPO_NO_C
     */
    public void setBpoNoC(String value) {
        setAttributeInternal(BPONOC, value);
    }

    /**
     * Gets the attribute value for BRAND_C using the alias name BrandC.
     * @return the BRAND_C
     */
    public String getBrandC() {
        return (String) getAttributeInternal(BRANDC);
    }

    /**
     * Sets <code>value</code> as attribute value for BRAND_C using the alias name BrandC.
     * @param value value to set the BRAND_C
     */
    public void setBrandC(String value) {
        setAttributeInternal(BRANDC, value);
    }

    /**
     * Gets the attribute value for END_USER_DESC_C using the alias name EndUserDescC.
     * @return the END_USER_DESC_C
     */
    public String getEndUserDescC() {
        return (String) getAttributeInternal(ENDUSERDESCC);
    }

    /**
     * Sets <code>value</code> as attribute value for END_USER_DESC_C using the alias name EndUserDescC.
     * @param value value to set the END_USER_DESC_C
     */
    public void setEndUserDescC(String value) {
        setAttributeInternal(ENDUSERDESCC, value);
    }

    /**
     * Gets the attribute value for FIT_C using the alias name FitC.
     * @return the FIT_C
     */
    public String getFitC() {
        return (String) getAttributeInternal(FITC);
    }

    /**
     * Sets <code>value</code> as attribute value for FIT_C using the alias name FitC.
     * @param value value to set the FIT_C
     */
    public void setFitC(String value) {
        setAttributeInternal(FITC, value);
    }

    /**
     * Gets the attribute value for ITEM_DESC_C using the alias name ItemDescC.
     * @return the ITEM_DESC_C
     */
    public String getItemDescC() {
        return (String) getAttributeInternal(ITEMDESCC);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_DESC_C using the alias name ItemDescC.
     * @param value value to set the ITEM_DESC_C
     */
    public void setItemDescC(String value) {
        setAttributeInternal(ITEMDESCC, value);
    }

    /**
     * Gets the attribute value for ORDER_QTY_C using the alias name OrderQtyC.
     * @return the ORDER_QTY_C
     */
    public String getOrderQtyC() {
        return (String) getAttributeInternal(ORDERQTYC);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_QTY_C using the alias name OrderQtyC.
     * @param value value to set the ORDER_QTY_C
     */
    public void setOrderQtyC(String value) {
        setAttributeInternal(ORDERQTYC, value);
    }

    /**
     * Gets the attribute value for SEASON_C using the alias name SeasonC.
     * @return the SEASON_C
     */
    public String getSeasonC() {
        return (String) getAttributeInternal(SEASONC);
    }

    /**
     * Sets <code>value</code> as attribute value for SEASON_C using the alias name SeasonC.
     * @param value value to set the SEASON_C
     */
    public void setSeasonC(String value) {
        setAttributeInternal(SEASONC, value);
    }

    /**
     * Gets the attribute value for STYLE_NAME_C using the alias name StyleNameC.
     * @return the STYLE_NAME_C
     */
    public String getStyleNameC() {
        return (String) getAttributeInternal(STYLENAMEC);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_NAME_C using the alias name StyleNameC.
     * @param value value to set the STYLE_NAME_C
     */
    public void setStyleNameC(String value) {
        setAttributeInternal(STYLENAMEC, value);
    }

    /**
     * Gets the attribute value for STYLE_NO_C using the alias name StyleNoC.
     * @return the STYLE_NO_C
     */
    public String getStyleNoC() {
        return (String) getAttributeInternal(STYLENOC);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_NO_C using the alias name StyleNoC.
     * @param value value to set the STYLE_NO_C
     */
    public void setStyleNoC(String value) {
        setAttributeInternal(STYLENOC, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @return the ATTRIBUTE16
     */
    public String getAttribute16() {
        return (String) getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @param value value to set the ATTRIBUTE16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @return the ATTRIBUTE17
     */
    public String getAttribute17() {
        return (String) getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @param value value to set the ATTRIBUTE17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @return the ATTRIBUTE18
     */
    public String getAttribute18() {
        return (String) getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @param value value to set the ATTRIBUTE18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @return the ATTRIBUTE19
     */
    public String getAttribute19() {
        return (String) getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @param value value to set the ATTRIBUTE19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @return the ATTRIBUTE20
     */
    public String getAttribute20() {
        return (String) getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @param value value to set the ATTRIBUTE20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @return the ATTRIBUTE21
     */
    public String getAttribute21() {
        return (String) getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @param value value to set the ATTRIBUTE21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @return the ATTRIBUTE22
     */
    public String getAttribute22() {
        return (String) getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @param value value to set the ATTRIBUTE22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @return the ATTRIBUTE23
     */
    public String getAttribute23() {
        return (String) getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @param value value to set the ATTRIBUTE23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @return the ATTRIBUTE24
     */
    public String getAttribute24() {
        return (String) getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @param value value to set the ATTRIBUTE24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @return the ATTRIBUTE25
     */
    public String getAttribute25() {
        return (String) getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @param value value to set the ATTRIBUTE25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @return the ATTRIBUTE26
     */
    public String getAttribute26() {
        return (String) getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @param value value to set the ATTRIBUTE26
     */
    public void setAttribute26(String value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @return the ATTRIBUTE27
     */
    public String getAttribute27() {
        return (String) getAttributeInternal(ATTRIBUTE27);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @param value value to set the ATTRIBUTE27
     */
    public void setAttribute27(String value) {
        setAttributeInternal(ATTRIBUTE27, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @return the ATTRIBUTE28
     */
    public String getAttribute28() {
        return (String) getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @param value value to set the ATTRIBUTE28
     */
    public void setAttribute28(String value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @return the ATTRIBUTE29
     */
    public String getAttribute29() {
        return (String) getAttributeInternal(ATTRIBUTE29);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @param value value to set the ATTRIBUTE29
     */
    public void setAttribute29(String value) {
        setAttributeInternal(ATTRIBUTE29, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @return the ATTRIBUTE30
     */
    public String getAttribute30() {
        return (String) getAttributeInternal(ATTRIBUTE30);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @param value value to set the ATTRIBUTE30
     */
    public void setAttribute30(String value) {
        setAttributeInternal(ATTRIBUTE30, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UnitName.
     * @return the UnitName
     */
    public String getUnitName() {
        return (String) getAttributeInternal(UNITNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UnitName.
     * @param value value to set the  UnitName
     */
    public void setUnitName(String value) {
        setAttributeInternal(UNITNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ShipmentUnit.
     * @return the ShipmentUnit
     */
    public String getShipmentUnit() {
        return (String) getAttributeInternal(SHIPMENTUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShipmentUnit.
     * @param value value to set the  ShipmentUnit
     */
    public void setShipmentUnit(String value) {
        setAttributeInternal(SHIPMENTUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attachemnt.
     * @return the Attachemnt
     */
    public Number getAttachemnt() {
        return (Number) getAttributeInternal(ATTACHEMNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attachemnt.
     * @param value value to set the  Attachemnt
     */
    public void setAttachemnt(Number value) {
        setAttributeInternal(ATTACHEMNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotOrdQty.
     * @return the TotOrdQty
     */
    public Number getTotOrdQty() {
        return (Number) getAttributeInternal(TOTORDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotOrdQty.
     * @param value value to set the  TotOrdQty
     */
    public void setTotOrdQty(Number value) {
        setAttributeInternal(TOTORDQTY, value);
    }

    /**
     * Gets the attribute value for ORDER_TYPE using the alias name OrderType.
     * @return the ORDER_TYPE
     */
    public String getOrderType() {
        return (String) getAttributeInternal(ORDERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_TYPE using the alias name OrderType.
     * @param value value to set the ORDER_TYPE
     */
    public void setOrderType(String value) {
        setAttributeInternal(ORDERTYPE, value);
    }

    /**
     * Gets the attribute value for DIVISION using the alias name Division.
     * @return the DIVISION
     */
    public String getDivision() {
        return (String) getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION using the alias name Division.
     * @param value value to set the DIVISION
     */
    public void setDivision(String value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for STYLE_NAME_NEW using the alias name StyleNameNew.
     * @return the STYLE_NAME_NEW
     */
    public String getStyleNameNew() {
        return (String) getAttributeInternal(STYLENAMENEW);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_NAME_NEW using the alias name StyleNameNew.
     * @param value value to set the STYLE_NAME_NEW
     */
    public void setStyleNameNew(String value) {
        setAttributeInternal(STYLENAMENEW, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyleNo.
     * @return the CurrentStyleNo
     */
    public String getCurrentStyleNo() {
        return (String) getAttributeInternal(CURRENTSTYLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyleNo.
     * @param value value to set the  CurrentStyleNo
     */
    public void setCurrentStyleNo(String value) {
        setAttributeInternal(CURRENTSTYLENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyleName.
     * @return the CurrentStyleName
     */
    public String getCurrentStyleName() {
        return (String) getAttributeInternal(CURRENTSTYLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyleName.
     * @param value value to set the  CurrentStyleName
     */
    public void setCurrentStyleName(String value) {
        setAttributeInternal(CURRENTSTYLENAME, value);
    }

    /**
     * Gets the attribute value for ERROR_MESSAGE using the alias name ErrorMessage.
     * @return the ERROR_MESSAGE
     */
    public String getErrorMessage() {
        return (String) getAttributeInternal(ERRORMESSAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MESSAGE using the alias name ErrorMessage.
     * @param value value to set the ERROR_MESSAGE
     */
    public void setErrorMessage(String value) {
        setAttributeInternal(ERRORMESSAGE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CustMnjOntBomRmlineLinesView.
     */
    public RowIterator getCustMnjOntBomRmlineLinesView() {
        return (RowIterator)getAttributeInternal(CUSTMNJONTBOMRMLINELINESVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CustMnjOntBomOblineDetailsView.
     */
    public RowIterator getCustMnjOntBomOblineDetailsView() {
        return (RowIterator)getAttributeInternal(CUSTMNJONTBOMOBLINEDETAILSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BomBpoLinesAllVO.
     */
    public RowIterator getBomBpoLinesAllVO() {
        return (RowIterator)getAttributeInternal(BOMBPOLINESALLVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BomLinesPRHistoryVO.
     */
    public RowIterator getBomLinesPRHistoryVO() {
        return (RowIterator)getAttributeInternal(BOMLINESPRHISTORYVO);
    }


    /**
     * Gets the associated <code>Row</code> using master-detail link FabricCustomReportVO.
     */
    public Row getFabricCustomReportVO() {
        return (Row)getAttributeInternal(FABRICCUSTOMREPORTVO);
    }

    /**
     * Sets the master-detail link FabricCustomReportVO between this object and <code>value</code>.
     */
    public void setFabricCustomReportVO(Row value) {
        setAttributeInternal(FABRICCUSTOMREPORTVO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MaterialSheetVO.
     */
    public RowIterator getMaterialSheetVO() {
        return (RowIterator)getAttributeInternal(MATERIALSHEETVO);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MnjBomPoDffVO.
     */
    public RowIterator getMnjBomPoDffVO() {
        return (RowIterator)getAttributeInternal(MNJBOMPODFFVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustMnjOntBomHeaderView1.
     */
    public RowSet getCustMnjOntBomHeaderView1() {
        return (RowSet)getAttributeInternal(CUSTMNJONTBOMHEADERVIEW1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> BuyerCriteria1.
     */
    public RowSet getBuyerCriteria1() {
        return (RowSet)getAttributeInternal(BUYERCRITERIA1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BuyerVO1.
     */
    public RowSet getBuyerVO1() {
        return (RowSet)getAttributeInternal(BUYERVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ZipperColorVO1.
     */
    public RowSet getZipperColorVO1() {
        return (RowSet)getAttributeInternal(ZIPPERCOLORVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ZipperFinishVO1.
     */
    public RowSet getZipperFinishVO1() {
        return (RowSet)getAttributeInternal(ZIPPERFINISHVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ZipperUniqueCodeVO1.
     */
    public RowSet getZipperUniqueCodeVO1() {
        return (RowSet)getAttributeInternal(ZIPPERUNIQUECODEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ZipperTypeVO1.
     */
    public RowSet getZipperTypeVO1() {
        return (RowSet)getAttributeInternal(ZIPPERTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ThreadSupplierCode1.
     */
    public RowSet getThreadSupplierCode1() {
        return (RowSet)getAttributeInternal(THREADSUPPLIERCODE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StyleNameVO1.
     */
    public RowSet getStyleNameVO1() {
        return (RowSet)getAttributeInternal(STYLENAMEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OperatingUnitsVO1.
     */
    public RowSet getOperatingUnitsVO1() {
        return (RowSet)getAttributeInternal(OPERATINGUNITSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SeasonLOV1.
     */
    public RowSet getSeasonLOV1() {
        return (RowSet)getAttributeInternal(SEASONLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StyleNoLOV1.
     */
    public RowSet getStyleNoLOV1() {
        return (RowSet)getAttributeInternal(STYLENOLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OrderTypeVO1.
     */
    public RowSet getOrderTypeVO1() {
        return (RowSet)getAttributeInternal(ORDERTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BomDivisionVO1.
     */
    public RowSet getBomDivisionVO1() {
        return (RowSet)getAttributeInternal(BOMDIVISIONVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ShipmentVO1.
     */
    public RowSet getShipmentVO1() {
        return (RowSet)getAttributeInternal(SHIPMENTVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ReqUnitName1.
     */
    public RowSet getReqUnitName1() {
        return (RowSet)getAttributeInternal(REQUNITNAME1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
