package mnj.ont.model.views;

import mnj.ont.model.entities.CustMnjOntBomOblineDetailsImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 27 10:38:57 BDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustMnjOntBomOblineDetailsViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BomId {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getBomId();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setBomId((Number)value);
            }
        }
        ,
        BomRmlineId {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getBomRmlineId();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setBomRmlineId((Number)value);
            }
        }
        ,
        BomOblineId {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getBomOblineId();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setBomOblineId((Number)value);
            }
        }
        ,
        SolineId {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getSolineId();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setSolineId((Number)value);
            }
        }
        ,
        SoObno {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getSoObno();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setSoObno((String)value);
            }
        }
        ,
        InseamId {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getInseamId();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setInseamId((String)value);
            }
        }
        ,
        SizeId {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getSizeId();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setSizeId((String)value);
            }
        }
        ,
        Linerefno {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getLinerefno();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setLinerefno((String)value);
            }
        }
        ,
        Barcode {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getBarcode();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setBarcode((String)value);
            }
        }
        ,
        ReleaseDate {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getReleaseDate();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setReleaseDate((Date)value);
            }
        }
        ,
        VersionNumber {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getVersionNumber();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setVersionNumber((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getVersionDate();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        LinkOafId {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getLinkOafId();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setLinkOafId((Number)value);
            }
        }
        ,
        EffectiveStartDate {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getEffectiveStartDate();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setEffectiveStartDate((Date)value);
            }
        }
        ,
        EffectiveEndDate {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getEffectiveEndDate();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setEffectiveEndDate((Date)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        SizeQuantity {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getSizeQuantity();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setSizeQuantity((Number)value);
            }
        }
        ,
        ItemCode {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getItemCode();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        LineNo {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getLineNo();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setLineNo((Number)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        Consumption {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getConsumption();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setConsumption((Number)value);
            }
        }
        ,
        WithExtra {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getWithExtra();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setWithExtra((Number)value);
            }
        }
        ,
        LegacyBomtrid {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getLegacyBomtrid();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setLegacyBomtrid((String)value);
            }
        }
        ,
        LegacyBomtrCid {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getLegacyBomtrCid();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setLegacyBomtrCid((String)value);
            }
        }
        ,
        LegacyId {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getLegacyId();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setLegacyId((String)value);
            }
        }
        ,
        CutP {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getCutP();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setCutP((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        ConsExtra {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getConsExtra();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setConsExtra((Number)value);
            }
        }
        ,
        MemoQty {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getMemoQty();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setMemoQty((String)value);
            }
        }
        ,
        Additional {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getAdditional();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAdditional((String)value);
            }
        }
        ,
        Inseam {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getInseam();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setInseam((String)value);
            }
        }
        ,
        DcpoNo {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getDcpoNo();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setDcpoNo((String)value);
            }
        }
        ,
        Color {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getColor();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        SizeVal {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getSizeVal();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setSizeVal((String)value);
            }
        }
        ,
        PoQty {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getPoQty();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setPoQty((Number)value);
            }
        }
        ,
        totalQty {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.gettotalQty();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.settotalQty((Number)value);
            }
        }
        ,
        InseamLov1 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getInseamLov1();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SizeLov1 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getSizeLov1();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FGItemsLOV1 {
            public Object get(CustMnjOntBomOblineDetailsViewRowImpl obj) {
                return obj.getFGItemsLOV1();
            }

            public void put(CustMnjOntBomOblineDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CustMnjOntBomOblineDetailsViewRowImpl object);

        public abstract void put(CustMnjOntBomOblineDetailsViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BOMID = AttributesEnum.BomId.index();
    public static final int BOMRMLINEID = AttributesEnum.BomRmlineId.index();
    public static final int BOMOBLINEID = AttributesEnum.BomOblineId.index();
    public static final int SOLINEID = AttributesEnum.SolineId.index();
    public static final int SOOBNO = AttributesEnum.SoObno.index();
    public static final int INSEAMID = AttributesEnum.InseamId.index();
    public static final int SIZEID = AttributesEnum.SizeId.index();
    public static final int LINEREFNO = AttributesEnum.Linerefno.index();
    public static final int BARCODE = AttributesEnum.Barcode.index();
    public static final int RELEASEDATE = AttributesEnum.ReleaseDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int LINKOAFID = AttributesEnum.LinkOafId.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int SIZEQUANTITY = AttributesEnum.SizeQuantity.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int LINENO = AttributesEnum.LineNo.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int CONSUMPTION = AttributesEnum.Consumption.index();
    public static final int WITHEXTRA = AttributesEnum.WithExtra.index();
    public static final int LEGACYBOMTRID = AttributesEnum.LegacyBomtrid.index();
    public static final int LEGACYBOMTRCID = AttributesEnum.LegacyBomtrCid.index();
    public static final int LEGACYID = AttributesEnum.LegacyId.index();
    public static final int CUTP = AttributesEnum.CutP.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int CONSEXTRA = AttributesEnum.ConsExtra.index();
    public static final int MEMOQTY = AttributesEnum.MemoQty.index();
    public static final int ADDITIONAL = AttributesEnum.Additional.index();
    public static final int INSEAM = AttributesEnum.Inseam.index();
    public static final int DCPONO = AttributesEnum.DcpoNo.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int SIZEVAL = AttributesEnum.SizeVal.index();
    public static final int POQTY = AttributesEnum.PoQty.index();
    public static final int TOTALQTY = AttributesEnum.totalQty.index();
    public static final int INSEAMLOV1 = AttributesEnum.InseamLov1.index();
    public static final int SIZELOV1 = AttributesEnum.SizeLov1.index();
    public static final int FGITEMSLOV1 = AttributesEnum.FGItemsLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustMnjOntBomOblineDetailsViewRowImpl() {
    }

    /**
     * Gets CustMnjOntBomOblineDetails entity object.
     * @return the CustMnjOntBomOblineDetails
     */
    public CustMnjOntBomOblineDetailsImpl getCustMnjOntBomOblineDetails() {
        return (CustMnjOntBomOblineDetailsImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for BOM_ID using the alias name BomId.
     * @return the BOM_ID
     */
    public Number getBomId() {
        return (Number) getAttributeInternal(BOMID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOM_ID using the alias name BomId.
     * @param value value to set the BOM_ID
     */
    public void setBomId(Number value) {
        setAttributeInternal(BOMID, value);
    }

    /**
     * Gets the attribute value for BOM_RMLINE_ID using the alias name BomRmlineId.
     * @return the BOM_RMLINE_ID
     */
    public Number getBomRmlineId() {
        return (Number) getAttributeInternal(BOMRMLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOM_RMLINE_ID using the alias name BomRmlineId.
     * @param value value to set the BOM_RMLINE_ID
     */
    public void setBomRmlineId(Number value) {
        setAttributeInternal(BOMRMLINEID, value);
    }

    /**
     * Gets the attribute value for BOM_OBLINE_ID using the alias name BomOblineId.
     * @return the BOM_OBLINE_ID
     */
    public Number getBomOblineId() {
        return (Number) getAttributeInternal(BOMOBLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOM_OBLINE_ID using the alias name BomOblineId.
     * @param value value to set the BOM_OBLINE_ID
     */
    public void setBomOblineId(Number value) {
        setAttributeInternal(BOMOBLINEID, value);
    }

    /**
     * Gets the attribute value for SOLINE_ID using the alias name SolineId.
     * @return the SOLINE_ID
     */
    public Number getSolineId() {
        return (Number) getAttributeInternal(SOLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOLINE_ID using the alias name SolineId.
     * @param value value to set the SOLINE_ID
     */
    public void setSolineId(Number value) {
        setAttributeInternal(SOLINEID, value);
    }

    /**
     * Gets the attribute value for SO_OBNO using the alias name SoObno.
     * @return the SO_OBNO
     */
    public String getSoObno() {
        return (String) getAttributeInternal(SOOBNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SO_OBNO using the alias name SoObno.
     * @param value value to set the SO_OBNO
     */
    public void setSoObno(String value) {
        setAttributeInternal(SOOBNO, value);
    }

    /**
     * Gets the attribute value for INSEAM_ID using the alias name InseamId.
     * @return the INSEAM_ID
     */
    public String getInseamId() {
        return (String) getAttributeInternal(INSEAMID);
    }

    /**
     * Sets <code>value</code> as attribute value for INSEAM_ID using the alias name InseamId.
     * @param value value to set the INSEAM_ID
     */
    public void setInseamId(String value) {
        setAttributeInternal(INSEAMID, value);
    }

    /**
     * Gets the attribute value for SIZE_ID using the alias name SizeId.
     * @return the SIZE_ID
     */
    public String getSizeId() {
        return (String) getAttributeInternal(SIZEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZE_ID using the alias name SizeId.
     * @param value value to set the SIZE_ID
     */
    public void setSizeId(String value) {
        setAttributeInternal(SIZEID, value);
    }

    /**
     * Gets the attribute value for LINEREFNO using the alias name Linerefno.
     * @return the LINEREFNO
     */
    public String getLinerefno() {
        return (String) getAttributeInternal(LINEREFNO);
    }

    /**
     * Sets <code>value</code> as attribute value for LINEREFNO using the alias name Linerefno.
     * @param value value to set the LINEREFNO
     */
    public void setLinerefno(String value) {
        setAttributeInternal(LINEREFNO, value);
    }

    /**
     * Gets the attribute value for BARCODE using the alias name Barcode.
     * @return the BARCODE
     */
    public String getBarcode() {
        return (String) getAttributeInternal(BARCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for BARCODE using the alias name Barcode.
     * @param value value to set the BARCODE
     */
    public void setBarcode(String value) {
        setAttributeInternal(BARCODE, value);
    }

    /**
     * Gets the attribute value for RELEASE_DATE using the alias name ReleaseDate.
     * @return the RELEASE_DATE
     */
    public Date getReleaseDate() {
        return (Date) getAttributeInternal(RELEASEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RELEASE_DATE using the alias name ReleaseDate.
     * @param value value to set the RELEASE_DATE
     */
    public void setReleaseDate(Date value) {
        setAttributeInternal(RELEASEDATE, value);
    }

    /**
     * Gets the attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @return the VERSION_NUMBER
     */
    public Number getVersionNumber() {
        return (Number) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @param value value to set the VERSION_NUMBER
     */
    public void setVersionNumber(Number value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for VERSION_DATE using the alias name VersionDate.
     * @return the VERSION_DATE
     */
    public Date getVersionDate() {
        return (Date) getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_DATE using the alias name VersionDate.
     * @param value value to set the VERSION_DATE
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for LINK_OAF_ID using the alias name LinkOafId.
     * @return the LINK_OAF_ID
     */
    public Number getLinkOafId() {
        return (Number) getAttributeInternal(LINKOAFID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINK_OAF_ID using the alias name LinkOafId.
     * @param value value to set the LINK_OAF_ID
     */
    public void setLinkOafId(Number value) {
        setAttributeInternal(LINKOAFID, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @return the EFFECTIVE_START_DATE
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @param value value to set the EFFECTIVE_START_DATE
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @return the EFFECTIVE_END_DATE
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @param value value to set the EFFECTIVE_END_DATE
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for SIZE_QUANTITY using the alias name SizeQuantity.
     * @return the SIZE_QUANTITY
     */
    public Number getSizeQuantity() {
        return (Number) getAttributeInternal(SIZEQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZE_QUANTITY using the alias name SizeQuantity.
     * @param value value to set the SIZE_QUANTITY
     */
    public void setSizeQuantity(Number value) {
        setAttributeInternal(SIZEQUANTITY, value);
    }

    /**
     * Gets the attribute value for ITEM_CODE using the alias name ItemCode.
     * @return the ITEM_CODE
     */
    public String getItemCode() {
        return (String) getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_CODE using the alias name ItemCode.
     * @param value value to set the ITEM_CODE
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for LINE_NO using the alias name LineNo.
     * @return the LINE_NO
     */
    public Number getLineNo() {
        return (Number) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_NO using the alias name LineNo.
     * @param value value to set the LINE_NO
     */
    public void setLineNo(Number value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for INVENTORY_ITEM_ID using the alias name InventoryItemId.
     * @return the INVENTORY_ITEM_ID
     */
    public Number getInventoryItemId() {
        return (Number) getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for INVENTORY_ITEM_ID using the alias name InventoryItemId.
     * @param value value to set the INVENTORY_ITEM_ID
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for CONSUMPTION using the alias name Consumption.
     * @return the CONSUMPTION
     */
    public Number getConsumption() {
        return (Number) getAttributeInternal(CONSUMPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for CONSUMPTION using the alias name Consumption.
     * @param value value to set the CONSUMPTION
     */
    public void setConsumption(Number value) {
        setAttributeInternal(CONSUMPTION, value);
    }

    /**
     * Gets the attribute value for WITH_EXTRA using the alias name WithExtra.
     * @return the WITH_EXTRA
     */
    public Number getWithExtra() {
        return (Number) getAttributeInternal(WITHEXTRA);
    }

    /**
     * Sets <code>value</code> as attribute value for WITH_EXTRA using the alias name WithExtra.
     * @param value value to set the WITH_EXTRA
     */
    public void setWithExtra(Number value) {
        setAttributeInternal(WITHEXTRA, value);
    }

    /**
     * Gets the attribute value for LEGACY_BOMTRID using the alias name LegacyBomtrid.
     * @return the LEGACY_BOMTRID
     */
    public String getLegacyBomtrid() {
        return (String) getAttributeInternal(LEGACYBOMTRID);
    }

    /**
     * Sets <code>value</code> as attribute value for LEGACY_BOMTRID using the alias name LegacyBomtrid.
     * @param value value to set the LEGACY_BOMTRID
     */
    public void setLegacyBomtrid(String value) {
        setAttributeInternal(LEGACYBOMTRID, value);
    }

    /**
     * Gets the attribute value for LEGACY_BOMTR_CID using the alias name LegacyBomtrCid.
     * @return the LEGACY_BOMTR_CID
     */
    public String getLegacyBomtrCid() {
        return (String) getAttributeInternal(LEGACYBOMTRCID);
    }

    /**
     * Sets <code>value</code> as attribute value for LEGACY_BOMTR_CID using the alias name LegacyBomtrCid.
     * @param value value to set the LEGACY_BOMTR_CID
     */
    public void setLegacyBomtrCid(String value) {
        setAttributeInternal(LEGACYBOMTRCID, value);
    }

    /**
     * Gets the attribute value for LEGACY_ID using the alias name LegacyId.
     * @return the LEGACY_ID
     */
    public String getLegacyId() {
        return (String) getAttributeInternal(LEGACYID);
    }

    /**
     * Sets <code>value</code> as attribute value for LEGACY_ID using the alias name LegacyId.
     * @param value value to set the LEGACY_ID
     */
    public void setLegacyId(String value) {
        setAttributeInternal(LEGACYID, value);
    }

    /**
     * Gets the attribute value for CUT_P using the alias name CutP.
     * @return the CUT_P
     */
    public Number getCutP() {
        return (Number) getAttributeInternal(CUTP);
    }

    /**
     * Sets <code>value</code> as attribute value for CUT_P using the alias name CutP.
     * @param value value to set the CUT_P
     */
    public void setCutP(Number value) {
        setAttributeInternal(CUTP, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ConsExtra.
     * @return the ConsExtra
     */
    public Number getConsExtra() {
        return (Number) getAttributeInternal(CONSEXTRA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ConsExtra.
     * @param value value to set the  ConsExtra
     */
    public void setConsExtra(Number value) {
        setAttributeInternal(CONSEXTRA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MemoQty.
     * @return the MemoQty
     */
    public String getMemoQty() {
        return (String) getAttributeInternal(MEMOQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MemoQty.
     * @param value value to set the  MemoQty
     */
    public void setMemoQty(String value) {
        setAttributeInternal(MEMOQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Additional.
     * @return the Additional
     */
    public String getAdditional() {
        return (String) getAttributeInternal(ADDITIONAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Additional.
     * @param value value to set the  Additional
     */
    public void setAdditional(String value) {
        setAttributeInternal(ADDITIONAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Inseam.
     * @return the Inseam
     */
    public String getInseam() {
        return (String) getAttributeInternal(INSEAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Inseam.
     * @param value value to set the  Inseam
     */
    public void setInseam(String value) {
        setAttributeInternal(INSEAM, value);
    }

    /**
     * Gets the attribute value for DCPO_NO using the alias name DcpoNo.
     * @return the DCPO_NO
     */
    public String getDcpoNo() {
        return (String) getAttributeInternal(DCPONO);
    }

    /**
     * Sets <code>value</code> as attribute value for DCPO_NO using the alias name DcpoNo.
     * @param value value to set the DCPO_NO
     */
    public void setDcpoNo(String value) {
        setAttributeInternal(DCPONO, value);
    }

    /**
     * Gets the attribute value for COLOR using the alias name Color.
     * @return the COLOR
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as attribute value for COLOR using the alias name Color.
     * @param value value to set the COLOR
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for SIZE_VAL using the alias name SizeVal.
     * @return the SIZE_VAL
     */
    public String getSizeVal() {
        return (String) getAttributeInternal(SIZEVAL);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZE_VAL using the alias name SizeVal.
     * @param value value to set the SIZE_VAL
     */
    public void setSizeVal(String value) {
        setAttributeInternal(SIZEVAL, value);
    }

    /**
     * Gets the attribute value for PO_QTY using the alias name PoQty.
     * @return the PO_QTY
     */
    public Number getPoQty() {
        return (Number) getAttributeInternal(POQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_QTY using the alias name PoQty.
     * @param value value to set the PO_QTY
     */
    public void setPoQty(Number value) {
        setAttributeInternal(POQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute totalQty.
     * @return the totalQty
     */
    public Number gettotalQty() {
        //return (Number) getAttributeInternal(TOTALQTY);
        
        Number total = new Number(0);
        Number rowValue = new Number(0);
        
        RowSetIterator iter=getViewObject().createRowSetIterator("totalqty");
        
        while(iter.hasNext()){
            Row row = iter.next();
            try{
                rowValue = (Number) row.getAttribute("SizeQuantity");
            }catch(Exception e){
               rowValue = new Number(0);
            }
            try{
                total=total.add(rowValue);
            }catch(Exception e){
                total = new Number(0);
            }
        }
        iter.reset();
        iter.closeRowSetIterator();
        
        return total;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute totalQty.
     * @param value value to set the  totalQty
     */
    public void settotalQty(Number value) {
        setAttributeInternal(TOTALQTY, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InseamLov1.
     */
    public RowSet getInseamLov1() {
        return (RowSet)getAttributeInternal(INSEAMLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SizeLov1.
     */
    public RowSet getSizeLov1() {
        return (RowSet)getAttributeInternal(SIZELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FGItemsLOV1.
     */
    public RowSet getFGItemsLOV1() {
        return (RowSet)getAttributeInternal(FGITEMSLOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
