package mnj.ont.model.entities;

import java.sql.CallableStatement;

import java.sql.SQLException;

import java.util.Map;

import javax.faces.application.FacesMessage;

import javax.faces.context.FacesContext;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;

import oracle.jdbc.OracleTypes;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 09 18:53:26 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustMnjOntBomHeaderImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    @Override
    protected void validateEntity() {
        if (getStyleNoC() == null && getStyleNameNew() == null ){        
            
           
            throw new JboException("You can't leave Style Name and Style No both Blank, please fill any one. .");
        
        }
        super.validateEntity(); 
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BomId {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getBomId();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setBomId((Number)value);
            }
        }
        ,
        BomNumber {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getBomNumber();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setBomNumber((Number)value);
            }
        }
        ,
        BomDate {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getBomDate();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setBomDate((Date)value);
            }
        }
        ,
        SaleorderId {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getSaleorderId();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setSaleorderId((Number)value);
            }
        }
        ,
        ItemCode {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getItemCode();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        BomStatus {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getBomStatus();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setBomStatus((String)value);
            }
        }
        ,
        RevisedRemarks {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getRevisedRemarks();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setRevisedRemarks((String)value);
            }
        }
        ,
        ReleaseDate {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getReleaseDate();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setReleaseDate((Date)value);
            }
        }
        ,
        VersionNumber {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getVersionNumber();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setVersionNumber((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getVersionDate();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        LinkOafId {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getLinkOafId();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setLinkOafId((Number)value);
            }
        }
        ,
        EffectiveStartDate {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getEffectiveStartDate();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setEffectiveStartDate((Date)value);
            }
        }
        ,
        EffectiveEndDate {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getEffectiveEndDate();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setEffectiveEndDate((Date)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getHeaderId();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getLineId();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        UserItemDescription {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getUserItemDescription();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setUserItemDescription((String)value);
            }
        }
        ,
        LegacyBomid {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getLegacyBomid();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setLegacyBomid((String)value);
            }
        }
        ,
        OrgId {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getOrgId();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        Post {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getPost();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setPost((String)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute11();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute12();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute13();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute14();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute15();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getBuyerId();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        BpoNoC {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getBpoNoC();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setBpoNoC((String)value);
            }
        }
        ,
        SeasonC {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getSeasonC();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setSeasonC((String)value);
            }
        }
        ,
        StyleNameC {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getStyleNameC();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setStyleNameC((String)value);
            }
        }
        ,
        StyleNoC {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getStyleNoC();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setStyleNoC((String)value);
            }
        }
        ,
        ItemDescC {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getItemDescC();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setItemDescC((String)value);
            }
        }
        ,
        BrandC {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getBrandC();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setBrandC((String)value);
            }
        }
        ,
        FitC {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getFitC();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setFitC((String)value);
            }
        }
        ,
        OrderQtyC {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getOrderQtyC();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setOrderQtyC((String)value);
            }
        }
        ,
        EndUserDescC {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getEndUserDescC();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setEndUserDescC((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute16();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute17();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute18();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute19();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute20();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute21 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute21();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute21((String)value);
            }
        }
        ,
        Attribute22 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute22();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute22((String)value);
            }
        }
        ,
        Attribute23 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute23();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute23((String)value);
            }
        }
        ,
        Attribute24 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute24();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute24((String)value);
            }
        }
        ,
        Attribute25 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute25();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute25((String)value);
            }
        }
        ,
        Attribute26 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute26();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute26((String)value);
            }
        }
        ,
        Attribute27 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute27();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute27((String)value);
            }
        }
        ,
        Attribute28 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute28();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute28((String)value);
            }
        }
        ,
        Attribute29 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute29();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute29((String)value);
            }
        }
        ,
        Attribute30 {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getAttribute30();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttribute30((String)value);
            }
        }
        ,
        ErrorMessage {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getErrorMessage();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setErrorMessage((String)value);
            }
        }
        ,
        OrderType {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getOrderType();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setOrderType((String)value);
            }
        }
        ,
        Division {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getDivision();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setDivision((String)value);
            }
        }
        ,
        StyleNameNew {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getStyleNameNew();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setStyleNameNew((String)value);
            }
        }
        ,
        CustMnjOntBomRmlineLines {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getCustMnjOntBomRmlineLines();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustMnjOntBomOblineDetails {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getCustMnjOntBomOblineDetails();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjBomBpoLinesAll {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getMnjBomBpoLinesAll();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjBomPoDffEO {
            public Object get(CustMnjOntBomHeaderImpl obj) {
                return obj.getMnjBomPoDffEO();
            }

            public void put(CustMnjOntBomHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CustMnjOntBomHeaderImpl object);

        public abstract void put(CustMnjOntBomHeaderImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BOMID = AttributesEnum.BomId.index();
    public static final int BOMNUMBER = AttributesEnum.BomNumber.index();
    public static final int BOMDATE = AttributesEnum.BomDate.index();
    public static final int SALEORDERID = AttributesEnum.SaleorderId.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int BOMSTATUS = AttributesEnum.BomStatus.index();
    public static final int REVISEDREMARKS = AttributesEnum.RevisedRemarks.index();
    public static final int RELEASEDATE = AttributesEnum.ReleaseDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int LINKOAFID = AttributesEnum.LinkOafId.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int USERITEMDESCRIPTION = AttributesEnum.UserItemDescription.index();
    public static final int LEGACYBOMID = AttributesEnum.LegacyBomid.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int POST = AttributesEnum.Post.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int BPONOC = AttributesEnum.BpoNoC.index();
    public static final int SEASONC = AttributesEnum.SeasonC.index();
    public static final int STYLENAMEC = AttributesEnum.StyleNameC.index();
    public static final int STYLENOC = AttributesEnum.StyleNoC.index();
    public static final int ITEMDESCC = AttributesEnum.ItemDescC.index();
    public static final int BRANDC = AttributesEnum.BrandC.index();
    public static final int FITC = AttributesEnum.FitC.index();
    public static final int ORDERQTYC = AttributesEnum.OrderQtyC.index();
    public static final int ENDUSERDESCC = AttributesEnum.EndUserDescC.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE27 = AttributesEnum.Attribute27.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE29 = AttributesEnum.Attribute29.index();
    public static final int ATTRIBUTE30 = AttributesEnum.Attribute30.index();
    public static final int ERRORMESSAGE = AttributesEnum.ErrorMessage.index();
    public static final int ORDERTYPE = AttributesEnum.OrderType.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int STYLENAMENEW = AttributesEnum.StyleNameNew.index();
    public static final int CUSTMNJONTBOMRMLINELINES = AttributesEnum.CustMnjOntBomRmlineLines.index();
    public static final int CUSTMNJONTBOMOBLINEDETAILS = AttributesEnum.CustMnjOntBomOblineDetails.index();
    public static final int MNJBOMBPOLINESALL = AttributesEnum.MnjBomBpoLinesAll.index();
    public static final int MNJBOMPODFFEO = AttributesEnum.MnjBomPoDffEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustMnjOntBomHeaderImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.CustMnjOntBomHeader");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for BomId, using the alias name BomId.
     * @return the BomId
     */
    public Number getBomId() {
        return (Number)getAttributeInternal(BOMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BomId.
     * @param value value to set the BomId
     */
    public void setBomId(Number value) {
        setAttributeInternal(BOMID, value);
    }

    /**
     * Gets the attribute value for BomNumber, using the alias name BomNumber.
     * @return the BomNumber
     */
    public Number getBomNumber() {
        return (Number)getAttributeInternal(BOMNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for BomNumber.
     * @param value value to set the BomNumber
     */
    public void setBomNumber(Number value) {
        setAttributeInternal(BOMNUMBER, value);
    }

    /**
     * Gets the attribute value for BomDate, using the alias name BomDate.
     * @return the BomDate
     */
    public Date getBomDate() {
        return (Date)getAttributeInternal(BOMDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BomDate.
     * @param value value to set the BomDate
     */
    public void setBomDate(Date value) {
        setAttributeInternal(BOMDATE, value);
    }

    /**
     * Gets the attribute value for SaleorderId, using the alias name SaleorderId.
     * @return the SaleorderId
     */
    public Number getSaleorderId() {
        return (Number)getAttributeInternal(SALEORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleorderId.
     * @param value value to set the SaleorderId
     */
    public void setSaleorderId(Number value) {
        setAttributeInternal(SALEORDERID, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for BomStatus, using the alias name BomStatus.
     * @return the BomStatus
     */
    public String getBomStatus() {
        return (String)getAttributeInternal(BOMSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BomStatus.
     * @param value value to set the BomStatus
     */
    public void setBomStatus(String value) {
        setAttributeInternal(BOMSTATUS, value);
    }

    /**
     * Gets the attribute value for RevisedRemarks, using the alias name RevisedRemarks.
     * @return the RevisedRemarks
     */
    public String getRevisedRemarks() {
        return (String)getAttributeInternal(REVISEDREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for RevisedRemarks.
     * @param value value to set the RevisedRemarks
     */
    public void setRevisedRemarks(String value) {
        setAttributeInternal(REVISEDREMARKS, value);
    }

    /**
     * Gets the attribute value for ReleaseDate, using the alias name ReleaseDate.
     * @return the ReleaseDate
     */
    public Date getReleaseDate() {
        return (Date)getAttributeInternal(RELEASEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReleaseDate.
     * @param value value to set the ReleaseDate
     */
    public void setReleaseDate(Date value) {
        setAttributeInternal(RELEASEDATE, value);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the VersionNumber
     */
    public Number getVersionNumber() {
        return (Number)getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNumber.
     * @param value value to set the VersionNumber
     */
    public void setVersionNumber(Number value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for VersionDate, using the alias name VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date)getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionDate.
     * @param value value to set the VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for LinkOafId, using the alias name LinkOafId.
     * @return the LinkOafId
     */
    public Number getLinkOafId() {
        return (Number)getAttributeInternal(LINKOAFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LinkOafId.
     * @param value value to set the LinkOafId
     */
    public void setLinkOafId(Number value) {
        setAttributeInternal(LINKOAFID, value);
    }

    /**
     * Gets the attribute value for EffectiveStartDate, using the alias name EffectiveStartDate.
     * @return the EffectiveStartDate
     */
    public Date getEffectiveStartDate() {
        return (Date)getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveStartDate.
     * @param value value to set the EffectiveStartDate
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for EffectiveEndDate, using the alias name EffectiveEndDate.
     * @return the EffectiveEndDate
     */
    public Date getEffectiveEndDate() {
        return (Date)getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveEndDate.
     * @param value value to set the EffectiveEndDate
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for UserItemDescription, using the alias name UserItemDescription.
     * @return the UserItemDescription
     */
    public String getUserItemDescription() {
        return (String)getAttributeInternal(USERITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserItemDescription.
     * @param value value to set the UserItemDescription
     */
    public void setUserItemDescription(String value) {
        setAttributeInternal(USERITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for LegacyBomid, using the alias name LegacyBomid.
     * @return the LegacyBomid
     */
    public String getLegacyBomid() {
        return (String)getAttributeInternal(LEGACYBOMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LegacyBomid.
     * @param value value to set the LegacyBomid
     */
    public void setLegacyBomid(String value) {
        setAttributeInternal(LEGACYBOMID, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for Post, using the alias name Post.
     * @return the Post
     */
    public String getPost() {
        return (String)getAttributeInternal(POST);
    }

    /**
     * Sets <code>value</code> as the attribute value for Post.
     * @param value value to set the Post
     */
    public void setPost(String value) {
        setAttributeInternal(POST, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for BpoNoC, using the alias name BpoNoC.
     * @return the BpoNoC
     */
    public String getBpoNoC() {
        return (String)getAttributeInternal(BPONOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoNoC.
     * @param value value to set the BpoNoC
     */
    public void setBpoNoC(String value) {
        setAttributeInternal(BPONOC, value);
    }

    /**
     * Gets the attribute value for SeasonC, using the alias name SeasonC.
     * @return the SeasonC
     */
    public String getSeasonC() {
        return (String)getAttributeInternal(SEASONC);
    }

    /**
     * Sets <code>value</code> as the attribute value for SeasonC.
     * @param value value to set the SeasonC
     */
    public void setSeasonC(String value) {
        setAttributeInternal(SEASONC, value);
    }

    /**
     * Gets the attribute value for StyleNameC, using the alias name StyleNameC.
     * @return the StyleNameC
     */
    public String getStyleNameC() {
        return (String)getAttributeInternal(STYLENAMEC);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleNameC.
     * @param value value to set the StyleNameC
     */
    public void setStyleNameC(String value) {
        setAttributeInternal(STYLENAMEC, value);
    }

    /**
     * Gets the attribute value for StyleNoC, using the alias name StyleNoC.
     * @return the StyleNoC
     */
    public String getStyleNoC() {
        return (String)getAttributeInternal(STYLENOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleNoC.
     * @param value value to set the StyleNoC
     */
    public void setStyleNoC(String value) {
        setAttributeInternal(STYLENOC, value);
    }

    /**
     * Gets the attribute value for ItemDescC, using the alias name ItemDescC.
     * @return the ItemDescC
     */
    public String getItemDescC() {
        return (String)getAttributeInternal(ITEMDESCC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDescC.
     * @param value value to set the ItemDescC
     */
    public void setItemDescC(String value) {
        setAttributeInternal(ITEMDESCC, value);
    }

    /**
     * Gets the attribute value for BrandC, using the alias name BrandC.
     * @return the BrandC
     */
    public String getBrandC() {
        return (String)getAttributeInternal(BRANDC);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrandC.
     * @param value value to set the BrandC
     */
    public void setBrandC(String value) {
        setAttributeInternal(BRANDC, value);
    }

    /**
     * Gets the attribute value for FitC, using the alias name FitC.
     * @return the FitC
     */
    public String getFitC() {
        return (String)getAttributeInternal(FITC);
    }

    /**
     * Sets <code>value</code> as the attribute value for FitC.
     * @param value value to set the FitC
     */
    public void setFitC(String value) {
        setAttributeInternal(FITC, value);
    }

    /**
     * Gets the attribute value for OrderQtyC, using the alias name OrderQtyC.
     * @return the OrderQtyC
     */
    public String getOrderQtyC() {
        return (String)getAttributeInternal(ORDERQTYC);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQtyC.
     * @param value value to set the OrderQtyC
     */
    public void setOrderQtyC(String value) {
        setAttributeInternal(ORDERQTYC, value);
    }

    /**
     * Gets the attribute value for EndUserDescC, using the alias name EndUserDescC.
     * @return the EndUserDescC
     */
    public String getEndUserDescC() {
        return (String)getAttributeInternal(ENDUSERDESCC);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndUserDescC.
     * @param value value to set the EndUserDescC
     */
    public void setEndUserDescC(String value) {
        setAttributeInternal(ENDUSERDESCC, value);
    }

    /**
     * Gets the attribute value for Attribute16, using the alias name Attribute16.
     * @return the Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute16.
     * @param value value to set the Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for Attribute17, using the alias name Attribute17.
     * @return the Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute17.
     * @param value value to set the Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for Attribute18, using the alias name Attribute18.
     * @return the Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute18.
     * @param value value to set the Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for Attribute19, using the alias name Attribute19.
     * @return the Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute19.
     * @param value value to set the Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for Attribute20, using the alias name Attribute20.
     * @return the Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute20.
     * @param value value to set the Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for Attribute21, using the alias name Attribute21.
     * @return the Attribute21
     */
    public String getAttribute21() {
        return (String)getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute21.
     * @param value value to set the Attribute21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for Attribute22, using the alias name Attribute22.
     * @return the Attribute22
     */
    public String getAttribute22() {
        return (String)getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute22.
     * @param value value to set the Attribute22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for Attribute23, using the alias name Attribute23.
     * @return the Attribute23
     */
    public String getAttribute23() {
        return (String)getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute23.
     * @param value value to set the Attribute23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for Attribute24, using the alias name Attribute24.
     * @return the Attribute24
     */
    public String getAttribute24() {
        return (String)getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute24.
     * @param value value to set the Attribute24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for Attribute25, using the alias name Attribute25.
     * @return the Attribute25
     */
    public String getAttribute25() {
        return (String)getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute25.
     * @param value value to set the Attribute25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for Attribute26, using the alias name Attribute26.
     * @return the Attribute26
     */
    public String getAttribute26() {
        return (String)getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute26.
     * @param value value to set the Attribute26
     */
    public void setAttribute26(String value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for Attribute27, using the alias name Attribute27.
     * @return the Attribute27
     */
    public String getAttribute27() {
        return (String)getAttributeInternal(ATTRIBUTE27);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute27.
     * @param value value to set the Attribute27
     */
    public void setAttribute27(String value) {
        setAttributeInternal(ATTRIBUTE27, value);
    }

    /**
     * Gets the attribute value for Attribute28, using the alias name Attribute28.
     * @return the Attribute28
     */
    public String getAttribute28() {
        return (String)getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute28.
     * @param value value to set the Attribute28
     */
    public void setAttribute28(String value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for Attribute29, using the alias name Attribute29.
     * @return the Attribute29
     */
    public String getAttribute29() {
        return (String)getAttributeInternal(ATTRIBUTE29);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute29.
     * @param value value to set the Attribute29
     */
    public void setAttribute29(String value) {
        setAttributeInternal(ATTRIBUTE29, value);
    }

    /**
     * Gets the attribute value for Attribute30, using the alias name Attribute30.
     * @return the Attribute30
     */
    public String getAttribute30() {
        return (String)getAttributeInternal(ATTRIBUTE30);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute30.
     * @param value value to set the Attribute30
     */
    public void setAttribute30(String value) {
        setAttributeInternal(ATTRIBUTE30, value);
    }

    /**
     * Gets the attribute value for ErrorMessage, using the alias name ErrorMessage.
     * @return the ErrorMessage
     */
    public String getErrorMessage() {
        return (String)getAttributeInternal(ERRORMESSAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ErrorMessage.
     * @param value value to set the ErrorMessage
     */
    public void setErrorMessage(String value) {
        setAttributeInternal(ERRORMESSAGE, value);
    }

    /**
     * Gets the attribute value for OrderType, using the alias name OrderType.
     * @return the OrderType
     */
    public String getOrderType() {
        return (String)getAttributeInternal(ORDERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderType.
     * @param value value to set the OrderType
     */
    public void setOrderType(String value) {
        setAttributeInternal(ORDERTYPE, value);
    }

    /**
     * Gets the attribute value for Division, using the alias name Division.
     * @return the Division
     */
    public String getDivision() {
        return (String)getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Division.
     * @param value value to set the Division
     */
    public void setDivision(String value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for StyleNameNew, using the alias name StyleNameNew.
     * @return the StyleNameNew
     */
    public String getStyleNameNew() {
        return (String)getAttributeInternal(STYLENAMENEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleNameNew.
     * @param value value to set the StyleNameNew
     */
    public void setStyleNameNew(String value) {
        setAttributeInternal(STYLENAMENEW, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCustMnjOntBomRmlineLines() {
        return (RowIterator)getAttributeInternal(CUSTMNJONTBOMRMLINELINES);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCustMnjOntBomOblineDetails() {
        return (RowIterator)getAttributeInternal(CUSTMNJONTBOMOBLINEDETAILS);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjBomBpoLinesAll() {
        return (RowIterator)getAttributeInternal(MNJBOMBPOLINESALL);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjBomPoDffEO() {
        return (RowIterator)getAttributeInternal(MNJBOMPODFFEO);
    }


    /**
     * @param bomId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number bomId) {
        return new Key(new Object[]{bomId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("CUST_MNJ_ONT_BOM_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setBomId(sVal);

    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        ViewObject vo =
            getDBTransaction().createViewObjectFromQueryStmt("select count(1) from CUST_MNJ_ONT_BOM_RMLINE h where h.BOM_ID =" +
                                                             getBomId());
        vo.first();
        int count = 0;
        try {
            count =
                    Integer.parseInt(vo.getCurrentRow().getAttribute(0).toString());
        } catch (Exception e) {
            vo.remove();
        }
        if (count == 0) {
            super.remove();
        } else {
            String messageText = "Child Records exists , can't delete";
            FacesMessage fm = new FacesMessage(messageText);
            fm.setSeverity(FacesMessage.SEVERITY_INFO);
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, fm);

        } //end of else
        vo.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        String user = (String)sessionScope.get("userId");

        if (DML_INSERT == operation) {
            try {
                
                setBomNumber(new oracle.jbo.domain.Number(getSrNoString()));
                setCreationDate((Date)Date.getCurrentDate());
                setCreatedBy(new oracle.jbo.domain.Number(user));
                

            } catch (SQLException f) {
                ;
            }
        }
        if (DML_UPDATE == operation) {
            try {
                setLastUpdateDate((Date)Date.getCurrentDate());
                setLastUpdatedBy(new oracle.jbo.domain.Number(user));
            } catch (SQLException f) {
                System.out.println(f.getMessage());
            }
        }
        super.doDML(operation, e);
    }

    public int getSrNoString() {
        int srno = 0;
        String stmt = "BEGIN :1 := cust_mnj_ont_pkg.megabom_srno; end;";
        CallableStatement cs =
            getDBTransaction().createCallableStatement(stmt, 1);
        try {
            cs.registerOutParameter(1, OracleTypes.VARCHAR);
            cs.execute();
            srno = cs.getInt(1);
            cs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return srno;
    }
}
